### ISSUE TITLE
Syncing ember data relationship

### ISSUE THREAD

**Issue by jrabary** [Addepar/ember-table#110]
Hi all,

I'm trying to render a table of data model that is in a relationship with another data model :

```
App.Model1 = DS.Model.extend {
  name: DS.attr('string')
  relation: DS.belongsTo('model2')
}

App.Model2 = DS.Model.extend {
  name: DS.attr('string')
}
```

In my table, I need to show the name of the associated model in a column. In my controller I have the following property : 

```
App.ApplicationController = Ember.DataController.extend {

  data:(->
     @map (item)->
         {relation: item.get('relation.name')
  ).property('model.@each')
}
```

Since Ember data load these two models asynchronously the `item.get('relation.name')` is defined after the table rendering and the cell remains empty. Is it possible to refresh the table after the data loading ?

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
