### ISSUE TITLE
Is column sorting included in the default feature set?

### ISSUE THREAD

**Issue by costeen2124** [Addepar/ember-table#113]
Just downloaded ember-table and starting to investigate it.  I noticed "isSortable" is a column configuration field that defaults to on.  Couple of questions
1. Does this represent "sort" or "moveable columns"?  I don't see any of the examples allowing a "sort".
2. Does the ability to click on a column header (or similar user interaction) and sort on the table's data included?

Thanks....

**Comment by azirbel** [comment]
This will be renamed with other API changes in https://github.com/Addepar/ember-table/issues/296.
