### ISSUE TITLE
Dynamic width resizing without window.resize

### ISSUE THREAD

**Issue by brian-gates** [Addepar/ember-table#114]
Ember table doesn't seem to resize its width except in response to window.resize.  It does not handle dynamic changes to the parent element.  

One can easily replicate the issue by going to http://addepar.github.io/#/ember-table/simple and enter $('.example-container').css('width', '10000px'); into the console.

May be related to #85.

**Comment by azirbel** [comment]
Here's another possible approach which I'm planning to explore when I get the chance: http://www.backalleycoder.com/2013/03/18/cross-browser-event-based-element-resize-detection/

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
