### ISSUE TITLE
Better namespacing

### ISSUE THREAD

**Issue by azirbel** [Addepar/ember-table#121]
Many names used by ember-table aren't correctly namespaced and could conflict with names used in the rest of the app. One example of this is registering Handlebars templates using Ember.TEMPLATES["template-name"] = (...).

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
