### ISSUE TITLE
Financial Table content?

### ISSUE THREAD

**Issue by neverfox** [Addepar/ember-table#125]
I've been pouring over the financial table example, and I cannot figure out how it gets any row data without a `content` property like all the other examples have. What feeds rows to `getCellContent`? From what I understand of the other examples, it shouldn't even work, but it obviously does. What is this black magic?

**Comment by Twinkletoes** [comment]
Do you have an example of using ember-table with a content source that returns a promise to an array of rows?
I'm seeing no rows even after the promise resolves when the page first renders. If I rerequest the server query, the data appears.

```
{{ember-table
	  height=400
	  hasFooter=false
	  enableContentSelection=false
	  columns=columns
	  contentBinding="players"
	}}
```

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
