### ISSUE TITLE
Feature request: row/column span

### ISSUE THREAD

**Issue by azirbel** [Addepar/ember-table#128]
For example, allow a row to span across multiple columns, or the width of the whole table, without being divided into cells.

First, we'd need to figure out the API for this (probably similar to HTML tables to keep things simple).

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
