### ISSUE TITLE
Full screen table doesn't resize when window resize

### ISSUE THREAD

**Issue by Bartheleway** [Addepar/ember-table#133]
When the window is resized, I also resize the container of the table (only the height, the width is handled automatically). The problem is that the table is resized, the scrollbars are also resized BUT it's not possible to scroll the content. I have to refresh the page to have the content scrollable.

I'm using Ember 1.5.0, jQuery 2.1.0, jQueryUI 1.10.4, ember-data 1.0.0-beta7.

**Comment by drglitch** [comment]
This might be a little late, but a really clean way to ensure ember table stays proper size is to hook onto `resize` event in didInsertElement and have it set grid's `gridHeight` property on every resize.

```javascript
var self = this;
var ensureSize = function() {
      var $container = $('#myGrid');
      self.set('gridHeight', ($(window).height())); //subtract pixels here for things like header, etc on page. or read $.height() from a container you'd like to track size of in case you're flexboxing.
}
$(window).on('resize', ensureSize);
ensureSize(); //just to make sure it happens on initial paint.
```

I found this method to be cleanest because (in just 6 lines of code) it sets the property that everything else inside ember table is hooked through, including various internal force-size-recalc calls.

**Comment by jrhe** [comment]
@daneeesh Doesn't work if the element itself is resized though. I thought the behaviour of your snippet was already in ember-table. 

There is also this pull request which works for everything but is a bit complex and hasn't been merged yet
https://github.com/Addepar/ember-table-addon/pull/19

**Comment by daneeesh** [comment]
@jrhe - you probably wanted to tag someone else. :)

**Comment by jrhe** [comment]
@daneeesh Oops. Apologies. I meant to tag @drglitch

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
