### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by loostro** [Addepar/ember-table#137]
I've decided to rename the original issue, as generally, the issue is docs are not clear enough.

To avoid spamming you with issues, I'll simply list all the things I think should be explained in docs.
## 1. Clearly state dependencies

I kept getting `Uncaught TypeError: Object [object Object] has no method 'resizable'` and `Uncaught TypeError: Object [object Object] has no method 'antiscroll'` errors when trying to run examples.

Turns out `ember-table` depends on [jQuery UI](https://github.com/jquery/jquery-ui) and [antiscroll](https://github.com/LearnBoost/antiscroll). These correct dependencies should be added to `bower.json` and/or at least mentioned in the docs.
## 2. How to set fixed height to the table and enable scrollbar?

When I copied the SimpleTable example it displayed all the 100 results (and no scrollbar). After some digging I found out the parent element needs a fixed height, which is not mentioned in the docs.

``` html+django
<div class="container-fluid" style="height: 500px;">
{{table-component
  hasFooter=false
  enableColumnReorder=true
  columnsBinding="columns"
  contentBinding="content"
}}
</div>
```
## 3. What is this `.coffee`? How do I use this?

One of the first problems I encountered was the examples are written in `CoffeeScript`. I didn't know what it was and this was the first "wall" stopping me from useing `ember-table`.

A short explanation (or at least [link](http://coffeescript.org/)) of what CoffeeScript is and a link to a converter like [http://js2coffee.org/](http://js2coffee.org/) would save some people time googleing and learning.
## 4. Why is it working so slow?

When I encountered problem `#2` (scroll up to see details) I also noticed that my app was working much slower than on the demo website. After adding a fixed height (which reduced the amount of of visible rows at a time) all the operations like _highlight on hover_, _reorder columns_, _resize columns_ started finally working at acceptable speed. Conclusion: **it could be caused by displaying too many rows at a time**.
## 5. Financial Table throws warnings and errors. Why?
- `WARNING: The 'bindAttr' view helper is deprecated in favor of 'bind-attr'` is self-explanatory, for those who are new to programming: in previous versions of ember we used `bindAttr`, which is now to be replaced with `bind-attr`. The old `bindAttr` has not been removed (yet) to not break users apps, but it throws this warning telling you should replace all the occurencies of `bindAttr` with `bind-attr` in your handlebars templates, becouse in future versions of ember the `bindAttr` will be removed. **Conclusion: we should fix the example code.**
- `Uncaught TypeError: Object 60269996.24879856 has no method 'toCurrency'` ~~it seems financial table is dependant on another library which is not documented or added in `bower.json`, I have yet to discover what it is :) probably [lucaong/jquery-toCurrency](https://github.com/lucaong/jquery-toCurrency) but not tested yet~~

`toCurrency` can be found in github repository [app/controllers/treetable.coffee](https://github.com/Addepar/ember-table/blob/81a5b913094302e8662585b2ecfaf375f67c8946/app/controllers/treetable.coffee#L4). **Conclusion: this code should also be copied to the website examples**.
## 6. How to display the financial table?

The code example from the website **does not work**:

``` html+django
{{table-component
  hasHeader=true
  hasFooter=false
  numFixedColumns=0
  rowHeight=35
  columnsBinding="columns"
  contentBinding="content"
}}
```

instead I managed to get it working by useing this snippet (copied from the actual example source):

``` html+django
{{view App.FinancialTableComponent dataBinding="data"}}
```

> Note: it's becouse the `{{table-component}}` renders the `Ember.Table.EmberTableComponent`. The financial table component extends that base component so in order to draw it, we have to directly reference it `{{view App.FinancialTableComponent}}`

If you want to use the `{{table-component}}` notation, you have to add this to your JS code (AFTER the `App.FinancialTableComponent` definition):

``` javascript
Ember.Handlebars.helper('financial-table-component', App.FinancialTableComponent);
```

Which allows you to use ``{{financial-table-component}}` notation. Ofcourse you can use another name.

**Conclusion: the doc needs updateing.**
## 7. How to load data from `ember-data`? Both for `RESTAdapter` and `FixturesAdapter`?

For `RESTAdapater` I've found [this anwser](http://stackoverflow.com/questions/18740910/ember-table-integration-with-ember-model-ember-data/18838636#18838636) on StackOverflow, however I have not yet tested it, however this [JSBin example](http://jsbin.com/eVOgUrE/3/edit) included in the anwser is working.

~~As for `FixturesAdapter` I don't know if the anwser above works and I don't know any other.
I'll be investigateing this right now :)~~ Now I can confirm it, the code from JSBin above **can be used with `FixturesAdapter`**, however it needs some customization.
## 8. How to correctly display Ajax example?

The website docs forget to mention the [App.EmberTableAjaxImageTableCell definition](https://github.com/Addepar/ember-table/blob/040f3a2a96870cd66f73b978890e73633d61c685/app/views/ember_table/ajax.coffee). Make sure your JS loads this table cell definition.

Also make sure you include the handlebars template for this view from [app/templates/ember_table/ajax_table/ajax_cell.hbs](https://github.com/Addepar/ember-table/blob/040f3a2a96870cd66f73b978890e73633d61c685/app/templates/ember_table/ajax_table/ajax_cell.hbs).

Also copy the `loading.gif` asset file from [app/assets/img/loading.gif](https://github.com/Addepar/ember-table/blob/040f3a2a96870cd66f73b978890e73633d61c685/app/assets/img/loading.gif) to `img` directory.
## 9. Version chaos

So, there is no clear versioning here:
- the website and `package.json` sais there is only one version: `v0.0.1`
- until a few days ago, there were tags for `v0.0.1`, `v0.0.2`, `v0.0.3`... up to `v0.1.2`, but they are removed now (why? what if someone had locked dependencies on these tags? this is really wrong)
- if you open the console, you will see `DEBUG: Ember Table : 0.0.2`

So.. which version am I actually useing? I understand that until `v1.0.0` the package is considered not stable and everything can change. I understand that you "reset" the version numbers to `v0.0.1`, but then you should create a github tag for this version and fix the debug message.

---

(... probably more comeing ...)

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
