### ISSUE TITLE
Feature request: fill table by columns instead of rows

### ISSUE THREAD

**Issue by Bartheleway** [Addepar/ember-table#140]
Hi,
here is something interesting to share with you. I'm currently building an app which use a lot of table layout. And more than that, I need a table filled with records as column and label as rows. Of course value field are input field so we can dynamically add columns (new record) or new line (new label).

To give a better idea, think about several tracks of an album. You can add/remove tracks from an album but you can also add properties to each tracks (like year, producer, ...).

Here is a small example:
|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| Record 1| Record 2 | ....
|  Label1  |   value1.1  |   value2.1  | .....
|  Label2  |   value1.2  |   value2.2  | .....

Do you think such thing would be possible ?

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
