### ISSUE TITLE
Working with asynchronous data (promises)

### ISSUE THREAD

**Issue by loostro** [Addepar/ember-table#144]
So, at the moment ember table does not work with promises. So all the data must be sideloaded in the route's model hook. Eg: 

If you want to create rows from `country.get('regions')` you must sideload all the regions:

``` js
model: function() {
  return this.store.find('country', 1);
  /* must return json with sideloaded regions
{
  "country": { "id": 1, "name": "USA", "regions": [ 0, 1, 2 ] },
  "regions": [
    { "id": 0, "country": 1, "name": "Alaska" },
    { "id": 1, "country": 1, "name": "Florida" },
    { "id": 2, "country": 1, "name": "California" }
  ]
}
   */
}
```

**And** the model definition `DS.belongsTo('country')` and `DS.hasMany('region')` must have `{async: false}` (which is the default), otherwise instead of an array of regions it will return a promise.

It would be super cool if rows could handle a promise, and when the promise is resolved, the table should be re-drawn. Before it is resolved, the table should remain empty (no rows).

**Comment by Twinkletoes** [comment]
I'd be up for making this work, as I need it too. What are the architectural issues involved?

**Comment by jwhitmarsh** [comment]
@BryanCrotaz did you get anywhere with this?

**Comment by BryanCrotaz** [comment]
Finished it and I think it's been merged

Bryan Crotaz
Silver Curve

On 20 May 2015, at 16:43, James <notifications@github.com> wrote:

@BryanCrotaz <https://github.com/BryanCrotaz> did you get anywhere with
this?

—
Reply to this email directly or view it on GitHub
<https://github.com/Addepar/ember-table/issues/144#issuecomment-103932445>.

**Comment by azirbel** [comment]
It's been merged in `ember-table-addon` (the transitional repository toward ember-cli). https://github.com/Addepar/ember-table-addon/pull/18

Once https://github.com/Addepar/ember-table/pull/309 is merged, it will be cherry-picked to this repository too.

**Comment by jwhitmarsh** [comment]
:+1: Thanks guys!

**Comment by BryanCrotaz** [comment]
It was surprisingly simple! Only took me about 20 mins.

On 21 May 2015 at 08:32, James <notifications@github.com> wrote:

> [image: :+1:] Thanks guys!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Addepar/ember-table/issues/144#issuecomment-104165253>
> .
>



-- 
Bryan Crotaz
Managing Director
Silver Curve

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
