### ISSUE TITLE
Reusable and extendable grid (nested tree) table component

### ISSUE THREAD

**Issue by loostro** [Addepar/ember-table#145]
I've created a resuable and extendable grid (nested tree) table component. At the moment I am working on my own project for a client, and deadline is really soon, so I won't probably have time to post the PR until next week. However, I'm opening this issue to ask @azirbel are there any special requirements for such a PR?

@neverfox this might interest you, as this component builds a nested tree from given items with configurable grouping (I've metioned it in #124)

if you change the `groupings` property -> the grid will be recalculated (there is an observer on `groupings`), so creating something like [SlickGrid](http://mleibman.github.io/SlickGrid/examples/example-grouping) is as easy as modifying `groupings` property

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
