### ISSUE TITLE
Financial Table Calculated Content with Promises

### ISSUE THREAD

**Issue by tatemz** [Addepar/ember-table#149]
This is not an issue, but only a question:

I have been working with Ember Table and the "financial" component in order to display parent-child models and their data. In doing so, I noticed that the `dataBinding` attribute in the [example template](https://github.com/Addepar/ember-table/blob/master/app/templates/ember_table/financial.hbs#L9) was bound with the `App.data.treedata` that is found in [treedata.coffee](https://github.com/Addepar/ember-table/blob/master/app/data/ember_table/treedata.coffee).

`App.data.treedata` is purely JSON. The complete example makes it seem that the parent cells are just sums of the nested child cells (where the smallest child contains the relevant values). I am attempting to calculate a JSON object to bind to the financial table in which parent rows are models and nested rows are child models by using Ember's `DS.hasMany` and `DS.belongsTo`.

The problem with this approach is that I must use Ember Promises in order to iterate over nested child models (which can only be done after an asynchronous request returns successful) by using `@get('childModels').then()`. This presents a problem as the view will be rendered **before** the PromiseArray can be used. I have a very robust code example, but before I dive deeper, do any experts in the room have any thoughts? I've been working on this issue for 3 weeks and am dying to figure it out.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
