### ISSUE TITLE
Table column groups?

### ISSUE THREAD

**Issue by loostro** [Addepar/ember-table#150]
Is it possible to "group" columns and allow to reorder only within the same group?

Eg. say I want a table like:

```
____________________________________________________
Country   | Suburban areas     |  Urban areas       \
          |--------------------|--------------------|
          | Av. age | Citizens | Av. age | Citizens |
----------|---------|----------|---------|----------|
USA       | 45      | 150m     | 36      | 200m     |
UK        | 42      | 50m      | 38      | 72m      |
Germany   | 48      | 58m      | 38      | 67m      |
----------|---------|----------|---------|----------/
```

I'd like to be able to "reorder"  Ubran areas and Suburban areas (the whole "group" of columns).

Well.. another thing is. Can you create column groups at all? I don't think its possible with the current ember-table.

There would be a couple of problems like:
- how to resize the colum groups?
- how to reorder columns / column groups?
- how to draw spanned cells (like "Urban areas" and "Suburban areas" header cells)?

I think some of them are easily answered:
- size of column group = sum of columns sizes (you cannot resize column group.. you can resize columns)
- reodering columns should be possible only within the column group
- reordering column groups should be possible (but only with other column groups..)
- spanned cells width should be equal to column group width (meaning, you can have only a cell spanning all other cells within that group) to keep things simple:

```
Table | A            | B            |
      | a1 | a2 | a3 | b1 | b2 | b3 |
------|----|----|----|----|----|----|
      | possible     | not| possible|
```

So.. scenario in column A -> cell spanning all columns in group "A" is possible.
Scenario in column B -> cell spanning "some" of columns in group "B" is not possible.

However, I don't know the internals of ember table well enough to implement such a feature, so I'm only posting it here as an idea.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
