### ISSUE TITLE
heightBinding does not synchronize the height of div.antiscroll-inner

### ISSUE THREAD

**Issue by macu** [Addepar/ember-table#152]
http://jsbin.com/zozonuxu/159#/test

I found that adjusting the table height through a height binding does not change the height of the `div.antiscroll-inner` element. The number of rows (`div.ember-table-table-row`) adjusts accordingly, but if the height has increased, the additional rows are invisible as overflow is hidden in `antiscroll-inner`. Workaround: Resizing the window or resizing a column causes the inner div to resize.

The example above also demonstrates another issue #107 where rows are not initially rendered when using a height binding.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
