### ISSUE TITLE
Horizontal scroll through mousewheel press doesn't work

### ISSUE THREAD

**Issue by Bartheleway** [Addepar/ember-table#169]
Let me explain a little bit the issue. On a standard mouse you got three buttons. Left click, right click and mousewheel. As some of you may know, you can press the mousewheel and drag your mouse making the content to scroll in all the possible 2D directions.

Antiscroll does provide support for such feature as tested on http://learnboost.github.io/antiscroll/. The issue is that ember-table doesn't forward correctly the scroll event because the vertical scroll through moushweel press works but not the horizontal scroll.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
