### ISSUE TITLE
General rendering issues

### ISSUE THREAD

**Issue by jrhe** [Addepar/ember-table#170]
In the latest Google Chrome (Roughly 35.0.1916.153, but I suspect it has autoupdated) I have been experiencing a number of rendering issues. Does anyone else have these problems and any idea how to debug them?

Last row not rendering:
![screen shot 2014-06-12 at 17 25 17](https://cloud.githubusercontent.com/assets/4038905/3302788/fa72cda2-f637-11e3-82b9-1acb6678fdb3.png)

Part of last row not rendering:
![screen shot 2014-06-12 at 17 25 26](https://cloud.githubusercontent.com/assets/4038905/3302789/fa747ea4-f637-11e3-839e-f534cea08ed3.png)

Top row not rendering:
![screen shot 2014-06-12 at 17 26 39](https://cloud.githubusercontent.com/assets/4038905/3302790/fa7806aa-f637-11e3-9e27-7708b6859aa1.png)

Row content getting stretched when rendered:
![screen shot 2014-06-13 at 19 42 37](https://cloud.githubusercontent.com/assets/4038905/3302791/fa7a4fa0-f637-11e3-93e1-e94325879c6e.png)

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
