### ISSUE TITLE
Mousewheel plugin should be optional ?

### ISSUE THREAD

**Issue by Bartheleway** [Addepar/ember-table#181]
Hi, I'm currently having a problem with mousewheel as declared in https://github.com/Addepar/ember-table/issues/169.

Because my application only use full screen tables, I don't really need the features of mousewheel. I already saw some plugins that have an optional dependency to mousewheel so I was wondering if we could do the same thing for ember-table or is it something completely mandatory ?

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
