### ISSUE TITLE
Feature: Add a way to 'decorate' a cell/header template

### ISSUE THREAD

**Issue by seriousben** [Addepar/ember-table#182]
Instead of creating multiple header class for different use cases, it would be great if I could just use add different mixins on my ColumnDef that would each add their own 'Layout' to the header and/or cell template.

Example Mixins: `SortableMixin`, `DropDownMixin`, `ContextMenuMixin`, `LazyLoadableMixin`

Right now, I need to create a `SortableDropDownContextMenyLazyLoadableTableHeader.hbs` to get all these features working.

So all of those need some markup to work, they all have their own actions, styling, rendering, etc...

Would be nice to have a way to make them render on top of each other inside of the ember-table-content div.

Not sure how possible this can be, but would definitely eliminate a lot of boilerplate.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
