### ISSUE TITLE
New example: Remote Sorting and Paging

### ISSUE THREAD

**Issue by seriousben** [Addepar/ember-table#183]
This example is built on top of the Ajax Table example:

http://jsbin.com/nefiwoco/15/edit

Is this something that could be added to the example? If you are interested in this, I can create a PR for it.

**Comment by cesar82** [comment]
@bradleypriest did you create a lazy-loaded table?

I need to create one but the documentation is not good, do you have any example that could share with me?

I really appreciate your support.

Thanks
