### ISSUE TITLE
Simple sort example

### ISSUE THREAD

**Issue by jasonf20** [Addepar/ember-table#184]
Hello,

I want to create the simplest form of sort in my application. Clicking the header should sort by that column. 

However I can't seem to figure out how best to do this. 

I have made a solution that works, but I think its not how it's supposed to be done. 
(My solution extends the TableComponent to set the sort action - but I think this default behaviour should not require this)

The lack of documentation and examples of features makes it quite difficult.

Could an example of Simple sorting be added?

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
