### ISSUE TITLE
Zooming issue in Firefox when numFixedColumns > 0

### ISSUE THREAD

**Issue by dempsesa** [Addepar/ember-table#196]
When using ctrl- on the browser, the data "disappears" (rows are visible when scrolled down all the way) when there is at least one fixed row. This can be seen on the Addepar example page with the financial table (http://addepar.github.io/#/ember-table/financial). If the page is refreshed after it has zoomed out, the data "reappears". I have seen this from Firefox 26+, currently using Firefox 31

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
