### ISSUE TITLE
Ember 1.7.x

### ISSUE THREAD

**Issue by jefflage** [Addepar/ember-table#199]
Ember 1.7.0 introduces several breaking changes to ember-table.  Primarily:

1.  `this.state` is deprecated for `this._state` on views/components
2.  `controller.content` is now readonly and you should only be setting `controller.model` instead

are you guys actively working on pulling in support for this?

**Comment by azirbel** [comment]
Looks like this is resolved, the app works with 1.7 to the best of my knowledge. Discussion for newer versions: https://github.com/Addepar/ember-table/issues/288.
