### ISSUE TITLE
Adding New Content - doesn't load into table

### ISSUE THREAD

**Issue by reidsteven75** [Addepar/ember-table#203]
I'm working on an application where I need the ability to add new content into Ember Table. 
Basically a user adds a record via a form, and that record is then appended to the content array that Ember Table uses in the 'content' for it's table. 
The tables are NOT fixed height so all the rows should be showing.
Everything works for the first 2 records that are added, but after that no more records are shown in the table.

Here's what happens as content is added:

Before 2 records are added:
- the last visible row has the class 'ember-table-last-row'
- there are 2 additional rows after the 'ember-table-last-row' which are not shown (have 'display:none')
  ![image](https://cloud.githubusercontent.com/assets/6345452/4127855/f63f2f1e-32ff-11e4-9b36-ae49b057474c.png)

After 2 records are added:
- previous 'display:none' rows are filled with new content
- the class 'ember-table-last-row' is no longer applied to any rows
- new rows aren't added when a new record is added to 'content' (although the table 'content' contains the new records)
  ![image](https://cloud.githubusercontent.com/assets/6345452/4127826/a2e58994-32ff-11e4-8b0e-9ca84cfe8ebc.png)

The weird thing is if I load or hide dev tools (elements, network, console, etc) in Chrome the new records are loaded into DOM and shown in the table.  I'm guessing there's some function that gets called to load these in but I don't know what triggers it, or how to call it. 

I've looked into every related issue on here but none of the solutions have worked.  Any insight would be greatly appreciated!

**Comment by skbly7** [comment]
I am still facing the same. And somehow using `$(window).trigger('resize');` isn't helping too. Any update on this issue?

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
