### ISSUE TITLE
Re-sizing the fluid table column bug 

### ISSUE THREAD

**Issue by moshemal** [Addepar/ember-table#205]
When re-sizing a column to much all the columns positioned to the left of it jump inside the table
![image](https://cloud.githubusercontent.com/assets/2989198/4217022/56f53546-38e2-11e4-943a-bba29cf5ddf5.png)

**Comment by azirbel** [comment]
This was an issue with `minWidth` not being respected. With the overhaul of column resizing in https://github.com/Addepar/ember-table/releases/tag/v0.4.0 this won't happen any more, and "fluid mode" is supported out of the box. Feel free to try it out at http://addepar.github.io/ember-table/#/ember-table/configurable-columns.
