### ISSUE TITLE
Cells do not re-render when content is updated unless scrolled out and back into view

### ISSUE THREAD

**Issue by brian-gates** [Addepar/ember-table#216]
Steps to reproduce:
1. Go to  http://addepar.github.io/ember-table/#/ember-table/simple
2. Enter this into the console:

```
App.__container__.lookup('controller:emberTable.simple').set('content.firstObject.open', 2)
```

Expected: 

The table should display the updated value.

Actual:

The table does not display the updated value.  Scrolling the item out of view and back into view does seem to refresh the value, however.

**Comment by azirbel** [comment]
Wow, good find @glennfu! That might make it much easier to track the issue down.

**Comment by SirZach** [comment]
thank you @glennfu for providing that solution! in my case, i was noticing that if i added another entry to the content array, embe-table would only render the first character and then stop. the mechanism to add another entry was inside of a modal dialog and there's some live-binding going on (not the best UI pattern and something I'll soon address).

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
