### ISSUE TITLE
Port project to ES6 style classes and convert to vanilla JS in the process.

### ISSUE THREAD

**Issue by intuitivepixel** [Addepar/ember-table#227]
Hi, I would like to use ember-table but it's developed against a prior version of Ember.js which used a  Handlebars version < 2.0. Since this recent update (http://emberjs.com/blog/2014/10/16/handlebars-update.html) ember-table is now incompatible to be used in a ember-cli project because the precompiled templates objects format has changed.. I did already some hacks using the latest ember-template-compiler to see if by using the latest version and Handlebars to 2.0 I could get the ember-table templates precompiled in the correct format, and it worked. Now what's left are the many Deprecation warnings because of global lookups etc. To get rid of them a rewrite would be needed, so I thought I'll try to spend 2/3 days getting this done (I would of course contribute it.) But now a question arises, Is someone already working on this? I'm asking this just to make sure I don't spent time on something already worked on...

Thanks in advance for any info.
Alex

**Comment by jrhe** [comment]
What are the various roles going to be for this repo, Addepar/ember-table-addon and the intuitivepixel/ember-cli-ember-table repos?

I'm currently using intuitivepixels repo as it fixes compatibility with the latest ember but I'm not sure if I should be. Additionally I have fixed #114 in it using a projectised version of the resize event code you referenced, ripping out the addepar resizing mixin. It works rather well.

**Comment by azirbel** [comment]
Good question @jrhe =)

Addepar/ember-table-addon is a work in progress. We are in fact working on it right now, and hope to have an official Ember-CLI-compatible version of Ember Table soon. Once that's done, it'll replace intuitivepixel/ember-cli-ember-table.

We're building a lot on work done in intuitivepixel/ember-cli-ember-table, but also rebuilding our demo app and adding simple tests.

Until our version is complete, keep using intuitivepixel's version (and big thanks to @intuitivepixel for making it!).

I would really love to have your fix to #114 - once the migration is done, hopefully it will be easy to copy your change to Addepar/ember-table-addon. There's nothing you need to do at the moment, though.

**Comment by jrhe** [comment]
Cheers for the clarification @azirbel :). I will add it once things are moved over. Will the main repo then be Addepar/ember-table-addon or will this repo still exist for holding the non CLI code?

**Comment by azirbel** [comment]
We'll try to make a backwards-compatible globals-based build; if we succeed, then we'll move all the new code into the ember-table repository.

**Comment by intuitivepixel** [comment]
@azirbel just found this article: http://pixelhandler.com/posts/develop-embercomponents-for-sharing-as-ember-cli-addons-a-practical-example and thought about you :) if you scroll at the bottom the author is exporting all the components as globals, exactly the setup you mentioned for ember-table to be also used as a standalone lib and ember-cli at the same time... cheers

**Comment by pete-the-pete** [comment]
Are there any more update about this effort?  I saw that @ebryn has some pull requests for handlebars2 and htmlbars, but those seem for the non-cli version.  I have tried using the addon versions, but I get multiple errors when using them with the latest ember and handlebars.

**Comment by azirbel** [comment]
`ember-table-addon` is merged as of #309!

HUGE thanks @intuitivepixel - your ideas and work here have been incredibly helpful.
