### ISSUE TITLE
Ember 1.8.x compatibility

### ISSUE THREAD

**Issue by marcemira** [Addepar/ember-table#229]
Hello, is it possible to update according to latests deprecations?
- Ember.Set / Ember.Get
- New lookup method for views.

Thanks in advance.

**Comment by azirbel** [comment]
This all seems to be fixed now - we've moved away from Ember.Set, and the table works with Ember 1.8. Other versions of Ember are discussed here: https://github.com/Addepar/ember-table/issues/288.
