### ISSUE TITLE
Navigation thru keyboard (scroll)

### ISSUE THREAD

**Issue by rainbow99984** [Addepar/ember-table#233]
Hi, scroll using arrow key is not working in Ember-table(mouse wheel working fine). Its simple table view with 30 column and 100 rows, only 20 are in display (limit by container height) this can be seen on http://addepar.github.io/#/ember-table/ajax
Thanks.
PS. Have posted it on SO but so far no answer that's why writing here 
http://stackoverflow.com/q/26523171/327504

**Comment by azirbel** [comment]
Thanks for posting here @rainbow99984, seems like an ember-table bug if anything. I'm not able to reproduce it, though: when I go to the ajax page you linked, click on a row, and hit up/down arrow keys, the content does scroll. (The selected row does not change). Are you seeing something different?

**Comment by testen** [comment]
It happens in firefox while in Chrome works fine.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
