### ISSUE TITLE
Conflict with prototype.js ($ notation )

### ISSUE THREAD

**Issue by rainbow99984** [Addepar/ember-table#235]
Hi, In project some places $ is directly used. eg. where conflict is been detected $.ui, $().mousewheel,  elementSizeDidChange function and for binding events. it will be good if it can be changed as jQuery or Ember.$ or jQuery is passed as argument in closure.
Thanks.

**Comment by azirbel** [comment]
This has been fixed in #309. Please reopen the issue if it's still a problem for you!
