### ISSUE TITLE
How to use ember model with table

### ISSUE THREAD

**Issue by vabatta** [Addepar/ember-table#239]
Hi,
I don't understand how to integrate an ember model (of ember-data) with the table.

`models/record.js`

``` js
export default DS.Model.extend({
  value: DS.attr('number'),
  date: DS.attr('string'),
  tag: DS.belongsTo('tag')
});
```

`models/tag.js`

``` js
export default DS.Model.extend({
  name: DS.attr('string'),
  records: DS.hasMany('Record', { async: true })
});
```

`routes/record.js`

``` js
export default Ember.Route.extend({
  model: function() {
    this.store.find('tag');

    var data = [];
    for (var i = 0; i < 1000; i++) {
      data.push(Em.Object.create({tag:Em.Object.create({name: "test"+i}), date: new Date(), value: i}));
    };
    //return data;
    return this.store.find('record').then(function(records) {
      return records.toArray();
    });
  }
});
```

`controllers/record.js`

``` js
export default Ember.ArrayController.extend({
  columns: function() {
    var tagCol = ColumnDefinition.create({
      columnWidth: 150,
      headerCellName: 'Tag',
      contentPath: '_data.tag.name',
      getCellContent: function(row) {
        return row.get('tag.name').toString();
      }
    });

    var dateCol = ColumnDefinition.create({
      columnWidth: 300,
      headerCellName: 'Data',
      getCellContent: function(row) {
        return row.get('date').toDateString();
      }
    });

    var valueCol = ColumnDefinition.create({
      columnWidth: 100,
      headerCellName: 'Valore',
      getCellContent: function(row) {
        return row.get('value').toFixed(2);
      }
    });

    return [tagCol, dateCol, valueCol];
  }.property()
});
```

`templates/record.hbs`

``` hbs
{{table-component
    hasFooter=false
    enableContentSelection=true
    columnsBinding="columns"
    contentBinding="model"
    height=400}}
```

While using the model with `this.store.find('record')` the table will be empty, otherwise if I use data (objects create manually) it works.

What's wrong?

Thanks!

**Comment by sirvine** [comment]
I spent way too long trying to debug why ember-table wouldn't convert bodyContent into rows. It turns out that this was the issue. Thanks!!

**Comment by Leooo** [comment]
Had the same issue, couldnt understand how to make the fix of @vabatta work, instead I added a maxHeight argument in my table-component (should be ~ the same impact):
  {{table-component
    hasFooter=false
    enableContentSelection=true
    columnsBinding="columns"
    contentBinding="model"
    rowHeight=200
    maxHeight=500
  }}

And then override _tableContentHeight:
  _tableContentHeight: Ember.computed(function() {
    return Math.min(this.get('maxHeight'),this.get('rowHeight') * this.get('bodyContent.length'));
  }).property('rowHeight', 'bodyContent.length','maxHeight'),

**Comment by Leooo** [comment]
@vabatta's fix is preventing the proper height to be computed on my side when loading data asynchronously, but I managed to have a table with fixed height and its initial rows displayed both when loading data synchronously and asynchronously by redisplaying the content when inserting the first views: in ```onNumChildViewsDidChange```:
```
  {{table-component
    hasFooter=false
    enableContentSelection=true
    columnsBinding="columns"
    contentBinding="model"
    rowHeight=70
    height=400
  }}
```
``javascript
      //return this.pushObjects(viewsToAdd);
      this.pushObjects(viewsToAdd);
      if (oldNumViews==0) this.viewportDidChange();
      return true;
```

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
