### ISSUE TITLE
Rendering issue in Linux Chrome v38

### ISSUE THREAD

**Issue by azirbel** [Addepar/ember-table#246]
Had to revert the fix to a rendering issue: https://github.com/Addepar/ember-table/pull/245.

This is potentially an issue again (may have been fixed by Chrome in the meantime). We should check it again and try to find a better fix.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
