### ISSUE TITLE
Deprecation warnings with Ember 1.8.1

### ISSUE THREAD

**Issue by mariuserik** [Addepar/ember-table#255]
Hi everyone.

After I've updated my application to use ember 1.8.1, I fixed the use of views of my application, but I sill get some deprecation warnings from inside ember-table.

In one simple ember-table jsbin example I get the same deprecation warnings in console (F12)
http://emberjs.jsbin.com/qabopacuku/1/edit

Screenshot:
![deprecation_warnings](https://cloud.githubusercontent.com/assets/1163058/5719472/46ba6874-9b19-11e4-9821-74376065b7fa.png)

Best Regards,

Marius

**Comment by intuitivepixel** [comment]
Please see here: https://github.com/Addepar/ember-table/issues/227 there is already work being done to fix this issues.
