### ISSUE TITLE
example bug in editable table

### ISSUE THREAD

**Issue by shaunc** [Addepar/ember-table#271]
I believe this:

    onRowContentDidChange: Ember.observer ->
      @set 'isEditing', no
    , 'rowContent'

Should be:

    onRowContentDidChange: Ember.observer ->
      @set 'isEditing', no
    , 'row.content'

**Comment by fivetwentysix** [comment]
@shaunc is this related to #263 ?

**Comment by shaunc** [comment]
This is not necessarily related -- this is a bug in the example on the website documentation. Sorry for not being more explicit. It is a simple typo, which you can see on http://addepar.github.io/ember-table/#/ember-table/editable

**Comment by azirbel** [comment]
@shaunc thanks for the note. I ninja-fixed it in #309 while converting to Ember CLI.
