### ISSUE TITLE
ember table with 100's if not 1000's of columns?....

### ISSUE THREAD

**Issue by iwellsltd** [Addepar/ember-table#272]
We're trying to use Ember Table to be dynamically populated from a REST dataset response and the number of columns could anywhere from 1 - 2000. Now trying the table with 1000's of columns it's either causing the page to become unresponsive or takes forever to load.

Is there please anyway to lazy load columns and potentially only load columns that are visible within the viewport?

**Comment by igillis** [comment]
I don't think this is a use case we've ever thought about. I'm having a hard time imagining a situation where a table with 2000 columns is useful to a user.

I think this is something you would have to put up a pull request for, though the best solution is probably just to add your own logic that decides which columns should actually be displayed at a given point in time.

**Comment by shaunc** [comment]
In fact, We have this problem as well. We have a spreadsheet tool, and spreadsheets sometimes can have very many columns. 

This is quite common -- e.g. after constructing a pivot table where both sets of items are large. The sheet itself is often just an intermediate step: display of a fragment of the table (as ember-table does wrt to rows) is usually sufficient, but allowing the user to scroll around in both directions is important.

**Comment by iwellsltd** [comment]
We are going to look at only displaying enough columns needed for the visible real estate and then polling for more on user scroll

**Comment by fivetwentysix** [comment]
:+1:

**Comment by igillis** [comment]
Interesting. Ember-table wasn't really designed as a spreadsheet, but we would definitely welcome a PR that added this lazy rendering of columns :)

**Comment by shaunc** [comment]
I would be interested in contributing... Currently, however, we are using "ember-cli-ember-table" ... any idea when and in what form (coffee vs es6) ember-cli version might be available? A PR that works with "ember-cli-ember-table" won't now work with master (or any other current branch??), and OTOH, intuitivepixel has referred all issues back to here.

**Comment by shaunc** [comment]
@iwellsltd -- btw: even wrt rows, ember-table current deals only with lazy render -- ie not creating DOM structures for unseen data. So work you are doing wrt to lazy loading from the server you will need anyway. We are ourselves wondering what to do when we have millions of rows -- of course a user will never actually scroll through millions of rows, but they might want to click on a page then scroll around from there. We are considering how to throw away rows (and columns) that are far from current position as well as load new ones when they get close to display window.

**Comment by azirbel** [comment]
@shaunc I'm still working on the conversion - you can see rough WIP at https://github.com/Addepar/ember-table-addon/tree/azirbel/demo-app-js. Sadly I had to put it aside two weeks ago to focus on some deadlines. Currently the demo app is ported to JS and includes the old version of ember-table via a bower dependency. I hope to finish the conversion in a couple weeks. Will be es6 and not coffee.

**Comment by shaunc** [comment]
@azirbel -- great -- thanks for the update! We will continue working w/ ember-cli-ember-table ourselves for the moment. Once you finish the port (or at least get a branch up) we will see how our "lazy-column" code (not yet working :)) fits in. 

Currently we are working in a class derived from ember table (and a few other views, etc). Is this the right approach, or, for a PR would you want integrated into core?

**Comment by azirbel** [comment]
That's a really good question. I think if this feature is done well and is generally usable, I'd love to have it integrated into Ember Table core. But for now, since the JS port of Ember Table isn't ready to go, you'll save a lot of hassle by writing it as an extension to Ember Table. Maybe once you've finished that, we can re-evaluate and see how it would look if it were integrated.

**Comment by shaunc** [comment]
@azirbel -- thanks. IMHO you have a lot of users interested in various different things. At some point you might want to think about supporting some features via mixins in any case, to prevent the core from getting unwieldy.

**Comment by iwellsltd** [comment]
We've decided to go with up to 250 columns for now which works just fine

**Comment by iwellsltd** [comment]
Oh @azirbel that's great news to hear the shift to ES6. We eagerly await for that release!

**Comment by Devonmusa** [comment]
I need  your help  @elevenelevensoftware   ,now  I  need to ember table with  150 columns , but is so slow!
How to solution this problem?

**Comment by elevenelevensoftware** [comment]
@Devonmusa I'm sorry this was a long time ago and I cannot remember how it was solved!
