### ISSUE TITLE
Remove dependency on row.isLoaded from row proxy

### ISSUE THREAD

**Issue by drglitch** [Addepar/ember-table#282]
Hello,

Right now, ember table expects its content to be a list of table.row objects. These objects are comprised of TableCell objects whose .cellContent is dependent on row data but also on row.isLoaded property.

Relating to lack of content update described in #216, this hard dependency forces an async data provider to assign a .isLoaded property to underlying row dataset in order to trigger cell/row updates in the view.

However, the table itself always requests data from content's ArrayProxy for each row it scrolls into view.
As such, for advanced implementations, it may be easier/quicker if table does not force use of .isLoaded flag to track data cell update but instead simply displays the data pushed to it from the content ArrayProxy.

In order to make in-place updates for underlying (local) datasets, it may be possible to simply have instance assigned to .content call .enumerableContentDidChange on the ArrayProxy assigned to .content to notify the table of the changes.

An even simpler way would be to create a way to force-flush the bindings and re-pull the data as requested in #216 

Looking forward to thoughts/comments! :)

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
