### ISSUE TITLE
Support Plan for Ember 1.8/1.9/1.10

### ISSUE THREAD

**Issue by azirbel** [Addepar/ember-table#288]
Ember 1.9 included an upgrade from Handlebars 1.0 to Handlebars 2.0, and Ember 1.10 replaced the templating library with HTMLBars. Because ember-table packages pre-compiled templates in our dist files, it's not possible for us to support future versions of Ember while also continuing to support users of ember-table who have not yet upgraded.

Our ideal strategy for dealing with this problem is to move to ember-cli; however, we need a solution for the meantime, and we need a solution that supports ember-table users who are not on ember-cli and are planning to continue using our globals build.

@ebryn, @Dylnuge, @igillis and I have all discussed this and come up with the following strategy:

At the moment, Ember Table supports Ember 1.4 through Ember 1.8. In the latest release (0.4.1), I have updated `bower.json` to reflect this.

I have created branches `ember-1.9` and `ember-1.10` to support using Ember Table with both of these versions of Ember.

At some point, we will merge these branches into Ember Table master. When we do, we will release "last version compatible with 1.X" releases. We will then stop supporting/updating the `ember-1.X` branches and may eventually delete them. If you plan to continue using Ember Table with previous versions of Ember after that, you will have to use the "last compatible releases", or maintain your own versions of Ember Table that use the appropriate template compilers (this is easy to do).

Independantly, we will move ember-table to an ember-cli addon. Once we do, the template compilation issue will disappear, as templates will be compiled within the consuming app. The long-term strategy is for apps which use Ember Table to migrate to ember-cli.

**Comment by joeruello** [comment]
Just want to say thanks alot for the effort and support. We're stuck on globals for at least the next couple of months and use Ember Table a lot in our App. This is a great help!

**Comment by cwiese** [comment]
I second that ... we can not move to HTMLBar yet!  Your work and this table is key to keeping people from trying out ng-Grid.

**Comment by SirZach** [comment]
a well thought out approach that appeases everyone. i'll start working off of the ember-1.10 branch and switch over to master or (hopefully) the ember-cli addon when it's ready. thanks!

**Comment by arenoir** [comment]
@azirbel how about merging in @intuitivepixel addon ember-cli-ember-table?   Then using a process like https://github.com/ef4/liquid-fire/tree/master/packaging to build precompiled packages for older versions of handlebars?

**Comment by azirbel** [comment]
Update: we've moved to Ember CLI structure and have a globals build (in `packaging`) which compiles to the `dist` folder (as before). This dist build is for Ember 1.8.

For now we are still maintaining the `ember-X.Y` branches. At some point we still plan to update the version targeted by the dist build, dropping compatibility for older versions at that point.
