### ISSUE TITLE
Using with ember-cli - Uncaught Error: Assertion Failed: ArrayProxy expects an Array or Ember.ArrayProxy, but you passed object

### ISSUE THREAD

**Issue by srisonti** [Addepar/ember-table#289]
I'm using ember-cli for a project and I'm having trouble getting ember-table to work with it. I installed the ember-table plugin via bower and included it with all of its dependencies in my Brocfile. Then, I created an orders controller (`app > controllers > orders.js`), and orders route (`app > routes > orders.js`), and an orders template (`app > templates > orders.hbs`).

To get started, I tried copying over one of the basic examples, but I've had no luck with it. Here's what my  orders controller file looks like:

      import Ember from 'ember';
      import config from '../config/environment';

      export default Ember.Controller.extend({
        page: 1,
        per_page: 25,
        sortAscending: false,
        sortColumn: null,
        content: Ember.computed(function() {
          var _i, _ref, _results;
          return (function() {
            _results = [];
            for (var _i = 0, _ref = this.get('per_page'); 0 <= _ref ? _i < _ref : _i > _ref; 0 <= _ref ? _i++ : _i--){ _results.push(_i); }
            return _results;
          }).apply(this).map(function(index) {
            var date;
            date = new Date();
            date.setDate(date.getDate() + index);
            return {
              date: date,
              open: Math.random() * 100 - 50,
              high: Math.random() * 100 - 50,
              low: Math.random() * 100 - 50,
              close: Math.random() * 100 - 50,
              volume: Math.random() * 1000000
            };
          });
        }).property('per_page'),
        columns: Ember.computed(function() {
          var closeColumn, dateColumn, highColumn, lowColumn, openColumn;
          dateColumn = Ember.Table.ColumnDefinition.create({
            columnWidth: 150,
            textAlign: 'text-align-left',
            headerCellName: 'Date',
            getCellContent: function(row) {
              return row.get('date').toDateString();
            }
          });
          openColumn = Ember.Table.ColumnDefinition.create({
            columnWidth: 100,
            headerCellName: 'Open',
            getCellContent: function(row) {
              return row.get('open').toFixed(2);
            }
          });
          highColumn = Ember.Table.ColumnDefinition.create({
            columnWidth: 100,
            headerCellName: 'High',
            getCellContent: function(row) {
              return row.get('high').toFixed(2);
            }
          });
          lowColumn = Ember.Table.ColumnDefinition.create({
            columnWidth: 100,
            headerCellName: 'Low',
            getCellContent: function(row) {
              return row.get('low').toFixed(2);
            }
          });
          closeColumn = Ember.Table.ColumnDefinition.create({
            columnWidth: 100,
            headerCellName: 'Close',
            getCellContent: function(row) {
              return row.get('close').toFixed(2);
            }
          });
          return [dateColumn, openColumn, highColumn, lowColumn, closeColumn];
        }),

        actions: {
          nextPage: function () {
            this.incrementProperty('page');
          },
          previousPage: function () {
            this.decrementProperty('page');
          },
        }

      });

And this is my orders route file:

        import Ember from 'ember';

        export default Ember.Route.extend({
          controllerName: 'orders',
          renderTemplate: function() {
            this.render('orders.headline', {
              outlet: 'headline'
            });
            this.render('orders.cta', {
              outlet: 'cta'
            });
            this.render('orders', {
              outlet: 'main'
            });
          }
        });

Nothing loads on the page and in console, I get the following error: `Uncaught Error: Assertion Failed: ArrayProxy expects an Array or Ember.ArrayProxy, but you passed object`.

And here's a couple of screenshots of my console:
![image](https://cloud.githubusercontent.com/assets/869246/6565430/eb880b88-c67d-11e4-9fe7-175464c03c95.png)
![image](https://cloud.githubusercontent.com/assets/869246/6565466/49e85070-c67e-11e4-81ab-833ff217fd27.png)

I've double- and triple-checked that `content` is a type Array (using `Ember.isArray`), so I'm really confused as to why this error is coming up. Is there something I'm missing in regards to how the controller and route are interacting? I don't know where this error is originating from. 

Thanks in advance for your help!

**Comment by akatov** [comment]
@srisonti did you manage to resolve this issue somehow?

**Comment by akatov** [comment]
Ah, figured it out myself. Just renamed the `content` property to something else.

Just for future reference: **Do not call your controller property `content`** - accessing content automatically tries to load the model provided by the route and ignores the controller property altogether.
