### ISSUE TITLE
Multiple selection is rather slow when using Shift + click selection

### ISSUE THREAD

**Issue by lygstate** [Addepar/ember-table#290]
I am selecting more than 100000 elements in a table.

**Comment by lygstate** [comment]
I think the storage of selected elements should be a set of intervals,
so that improve the performance of select all and select a large set of elements.

**Comment by azirbel** [comment]
Thanks for the note! It would definitely be great to improve performance here, as ember-table is built to handle large numbers of elements, but there's a lot to consider:

The main advantage of using an array of objects is that it works well with two-way data binding. Two-way data binding makes the selection API really simple, but we may have to rethink it as an architectural decision someday.

Two-way binding implies that the selection can be modified both inside and outside the table component. So if you hit select-all in the table, it should set `selection` to a list of all the elements. But you could also add a button outside of the table (say, "highlight rows with values over 20"), which would search through the table's underlying content, find the desired rows, and set `selection` to the result. This would then propagate _into_ ember-table, visualizing the custom selection.

There's a nice side-effect to this, too: if you reload the table, but still have `selection` bound to the outer controller/component, the newly loaded table will still have the same selection as before.

Those are the main advantages of the current architecture.

I can envision a "data down, bindings up" selection API in which the table internally stores `selection` as a set of intervals. But even then, I'm not sure it would be faster. When you select all, presumably you still want access to all the selected elements, so it may be hard to avoid O(n)-ish bindings...

If this matters to you, I'd suggest taking a look at how rows check whether they are selected (`isSelected`), as this is probably the slow part. Maybe we can optimize this without changing the architecture.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
