### ISSUE TITLE
Body content doesn't refresh the content below the table height when dynamically loaded through filtering

### ISSUE THREAD

**Issue by Leooo** [Addepar/ember-table#292]
Ember 1-10 branch

When loading content as an array everything is fine:

``` javascript
  model: function(){
   return this.store.find('relationship').then(function(rels){
      return rels.toArray();
    });
  },
```

When loading a content through a model and using a `find` promise, this is fine too  (outside of the height trick in https://github.com/Addepar/ember-table/issues/239):

``` javascript
  model: function(){
    return this.store.find('relationship');
  },
```

Now I want my table to be refreshed when adding future relationships instances, so Im using filters (see http://emberjs.com/guides/models/frequently-asked-questions/). But then the Ember.Table.Row s below the height of the screen have no content, and when I scroll down I can only see the loaders (perpetually):

``` javascript
  model: function(){
    return this.store.filter('relationship',function(rel){
      return true;
    });
  },
```

This is solved for me by changing the computedproperty `bodyContent` as dependent of `.property('content.@each')` instead of `.property('content')`

**Comment by azirbel** [comment]
Good find! I think we should depend on `content.[]` instead of `content.@each` (stylistic change) but I think you're right. PRs are welcome, or if you wait for a while I'll make the change in the ember-table-addon repository.

**Comment by Leooo** [comment]
Hard to find explanations of the differences between .[] and .@each, but when I look at http://stackoverflow.com/questions/22088746/computed-property-in-ember-based-on-async-data it seems like @.each is better if we want to refresh bodyContent whenever one row is modified, not just when one row is added / removed.

**Comment by Truffula** [comment]
I'm having a similar issue, using `ember-table-addon`, with:

```js
model: function () {
    return this.store.all('store');
},
```

and I've found that it varies with the complexity of the table (i.e. with less columns, it is more likely to fail, and in some cases there's a fairly consistent cutoff as you add more columns, which appears consistent across Chrome + Safari). If there are two tables on the same route, and one of them has sufficient columns, sometimes the other will also work fine (but not always). Also, if you come from another route with a working table, it will generally work.

I suspect there's an observer not firing somewhere (and/or perhaps a race condition), but I've been digging for a while and haven't been able to find the cause. Changing the `bodyContent` property to observe `content.[]` (as per @Leooo's last comment) didn't fix.

**Comment by Truffula** [comment]
I'm having a similar issue, using `ember-table-addon`, with:

```js
model: function () {
    return this.store.all('store');
},
```

and I've found that it varies with the complexity of the table (i.e. with less columns, it is more likely to fail, and in some cases there's a fairly consistent cutoff as you add more columns, which appears consistent across Chrome + Safari). If there are two tables on the same route, and one of them has sufficient columns, sometimes the other will also work fine (but not always). Also, if you come from another route with a working table, it will generally work.

I suspect there's an observer not firing somewhere (and/or perhaps a race condition), but I've been digging for a while and haven't been able to find the cause. Changing the `bodyContent` property to observe `content.[]` (as per @Leooo's comment) didn't fix.

**Comment by azirbel** [comment]
We now observe `content.[]` on the master branch. @Leooo is your issue resolved? @Truffula if you still have problems, could you open a separate issue?

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
