### ISSUE TITLE
Testing Framework and Adding Tests

### ISSUE THREAD

**Issue by jimnanney** [Addepar/ember-table#293]
The biggest drawback I see for ember-table and keeping current with ember is the lack of unit/acceptance tests. I realize the documentation states the tests will come when a testing framework is decided upon. Is it safe to assume that the test framework of choice is qunit and ember-qunit since ember and ember-cli both advocate for this?

If it is, would it be in vein for me to start writing tests for a pull request to the project? I would prefer to do it with ember-cli and ember-1.11, but until the addon work is completed, including ember-qunit as a dev-dependency would likely suffice.

Also as it stands currently, the existential tests that do exist, fail.  They can be made to pass by updating the location of the jquery included in Gruntfile.js as follows:

```
-              'vendor/jquery/jquery.js',
+              'vendor/jquery/dist/jquery.js',
```

I'd be happy to start adding tests if qunit will indeed be the test framework. We are embarking on a major Ember app at work, and plan to use ember-table throughout. I would feel much safer with unit tests in place especially given the frequent release cycle of Ember itself.

**Comment by azirbel** [comment]
I agree that we really need tests. They're high on our wishlist, but there always seems to be more pressing work. Right now that's the ember-cli migration.

Thanks for the offer to help out!

We do plan to use the standard ember cli test setup, and would love some help writing tests.

If I were you, I would start writing tests directly against our work-in-progress ember-cli version: https://github.com/Addepar/ember-table-addon. You can make a PR against that repo, or write tests now but wait until it's merged to submit your PR.

**Comment by jimnanney** [comment]
I'll clone that repo and write my tests against it, and send along the PR. Happy to know you have the ember-cli addon in the works.

**Comment by azirbel** [comment]
@jimnanney we've moved to Ember CLI - it should be easier to add tests now by following the Ember CLI style.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
