### ISSUE TITLE
Do not update _tableScrollTop

### ISSUE THREAD

**Issue by andrewfan** [Addepar/ember-table#294]
Hello,
why are we setting `_tableScrollTop` to `0` in `didInsertElement` hook
https://github.com/Addepar/ember-table/blob/074ad3dcfbbe7c47a5e2a014c293030dc652ad85/src/component.coffee#L272
when it is `0` by default? it will cause additional CPs, observers recalculations
https://github.com/Addepar/ember-table/blob/074ad3dcfbbe7c47a5e2a014c293030dc652ad85/src/component.coffee#L181?

**Comment by andrewfan** [comment]
i found a workaround for it 
```javascript
    didInsertElement: function() {
      Ember.beginPropertyChanges();
      this._super();
      this.setScrollTop();
      Ember.endPropertyChanges();
    },
     setScrollTop: function() {
      var rowHeight = get(this, 'rowHeight'),
      scrollTop = get(this, 'topOffset') * rowHeight || 0;
      set(this, '_tableScrollTop', scrollTop);
    },

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
