### ISSUE TITLE
RFC: API Changes for v1.0.0

### ISSUE THREAD

**Issue by azirbel** [Addepar/ember-table#296]
Before releasing a 1.0 version of Ember Table, we want to make some small changes to the API since it'll be harder to change it in the future while maintaining [SemVer](http://semver.org/).

The theme here is renaming and cleanup. Some people have suggested larger-scale restructuring — this will wait until Ember Table 2.0.

Before making these changes, we will release a version where both old and new versions of the API work (with `Ember.deprecate` to guide users in their migration to the new version). We will then release a new version with the old API removed. This should make it easy to upgrade to the new API.  Also, the changes proposed here will happen **after** the Ember CLI version of Ember Table is released.

This issue is a place for discussion — feel free to comment on changes or suggest new ones. We're especially interested in ideas that simplify the API, reducing the number of settings while preserving the same behavior.

See a description of these options on the [documentation page](http://addepar.github.io/ember-table/#/ember-table/documentation).
### EmberTableComponent

| Current API | New API | Explanation |
| --- | --- | --- |
| **content** | **data** | Removes confusion with "content" and "model", which both have Ember meanings. Also more consistent with ember-charts, and more intuitive (a table displays data). |
| columns | columns |  |
| numFixedColumns | numFixedColumns |  |
| **numFooterRow** | **numFooterRows** | More consistent with `numFixedColumns`. |
| rowHeight | rowHeight |  |
| **minHeaderHeight** |  | This should just be `rowHeight`. Advanced users can extend Ember Table and add this as custom behavior if they really need it. |
| **footerHeight** |  | This should be an internal property, defined by `numFooterRows * rowHeight`. |
| hasHeader | hasHeader |  |
| **hasFooter** |  | Control this via `numFooterRows`, which will default to 0 (no footer) |
| **enableColumnReorder** |  | Control this via `isReorderable` on the columns. If no columns are reorderable, the behavior will be the same as if `enableColumnReorder` was set to false. |
| enableContentSelection | enableContentSelection |  |
| columnMode | columnMode |  |
| selectionMode | selectionMode |  |
| selection (output) | selection (output) |  |
| classNames | classNames |  |
| classNameBindings | classNameBindings |  |
| **styleBindings** |  | Already undocumented; can be used as a power user feature, but not part of the official API. Recommended to use `classNameBindings` instead to style your table. |
### ColumnDefinition

| Current API | New API | Explanation |
| --- | --- | --- |
| **headerCellName** | **name** | Simpler wording - this is used within `ColumnDefinition.create`, so the context is already clear. |
| contentPath | contentPath |  |
| minWidth | minWidth |  |
| maxWidth | maxWidth |  |
| savedWidth | savedWidth |  |
| isResizable | isResizable |  |
| **isSortable** | **isReorderable** | This has caused a lot of confusion. We use "jQuery sortable" but the behavior is column reordering, unrelated to sorting. |
| textAlign | textAlign |  |
| canAutoResize | canAutoResize |  |
| **headerCellViewClass** | **headerCellView** | The type of this option is a string, not a class. |
| **tableCellViewClass** | **tableCellView** | The type of this option is a string, not a class. |
| getCellContent | getCellContent |  |
| setCellContent | setCellContent |  |
### TableCell

| Current API | New API | Explanation |
| --- | --- | --- |
| templateName | templateName |  |
| classNames | classNames |  |
| classNameBindings | classNameBindings |  |
| **styleBindings** |  | Hard to use, and recommended to use `classNameBindings` instead to style your cells. |
### HeaderCell

| Current API | New API | Explanation |
| --- | --- | --- |
| templateName | templateName |  |
| classNames | classNames |  |
| classNameBindings | classNameBindings |  |
| **styleBindings** |  | Hard to use, and recommended to use `classNameBindings` instead to style your cells. |

**Comment by ebryn** [comment]
This looks good to me. I'd like to start a discussion around how we can componentize things more and maybe the components can use newer APIs sooner than the existing view-based APIs.

**Comment by cwiese** [comment]
Yes…been talking with Jaca about that too.

I do have questions around Components, the Resolver and PODS when I have small Render templates besides the main template ….

**Comment by azirbel** [comment]
@ebryn yep, I think there's lots of restructuring discussion coming up, but we'll try to release a 1.0 version before we get too far into it.

**Comment by azirbel** [comment]
Something that will break: using `numFooterRows` (defaults to 0) and removing `hasFooter` (defaults to `true`) will mean the table has no footer by default, instead of having one by default. I think this is the correct behavior.

**Comment by artych** [comment]
Looks like there are no component actions in 1.0? Are you expecting "data down, actions up" behaviour?
I'd would be happy if at least something like `actionRowSelected(lastSelectedRow, allSelectedRows)` action appeared. 
PS Anyway thank you for this great work!

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
