### ISSUE TITLE
Help Wanted: Testing new Ember-CLI-based version

### ISSUE THREAD

**Issue by azirbel** [Addepar/ember-table#300]
For a while now, we've been working on converting Ember Table to ember-cli style. The new version is almost ready to go - but because of all the ways Ember Table can be extended, I'm hoping the community can help test it out before we merge it.

The new version lives at [github.com/Addepar/ember-table-addon](https://github.com/Addepar/ember-table-addon). (The name is temporary; we will eventually release this work as "ember-table".)

It is fully backwards-compatible for people who use a globals-based build and can't migrate to ember-cli yet. (We can't promise support for this indefinitely; move to ember-cli!)

## Help Wanted

* Testing backwards compatibilty. Does swapping your bower dependency to use `ember-table-addon` work out of the box?
* Testing Ember Table in an Ember CLI environment. Are there any problems e.g. extending ember-table or specifying different table cell views?

If you can help out, leave a comment here! Even a "tried it in my app, seems to work" comment is helpful.

#### Ember CLI

```bash
# ember-cli >= 0.2.0
ember install:addon Addepar/ember-table-addon

# ember-cli >= 0.2.3
npm install --save-dev Addepar/ember-table-addon
ember g ember-table
```

#### Globals/Bower

Use the same import process you currently have, but swap out your `ember-table` bower dependency for `Addepar/ember-table-addon`.

```js
// bower.json
"dependencies": {
  "ember-table": "Addepar/ember-table-addon"
}
```

Or, if you are using the `dist` js and css directly, swap out the included files:

```
Addepar/ember-table/v0.4.1/dist/ember-table.css
    -> Addepar/ember-table-addon/master/dist/ember-table.css

Addepar/ember-table/v0.4.1/dist/ember-table.js
    -> Addepar/ember-table-addon/master/dist/ember-table.js
```

For example, here is a JS Bin that uses the global version: http://emberjs.jsbin.com/wedahatixe/1

## Using with Ember CLI

Many file names have changed, and if you want to extend Ember Table, make sure to import it using the new import style:

```
import ColumnDefinition from 'ember-table/models/column-definition';
...
var name = ColumnDefinition.create({...});
```

For help migrating, check out the new demo app and corresponding code at [addepar.github.io/ember-table-addon](http://addepar.github.io/ember-table-addon/#/overview). (Side note: docs there are automatically built from the actual files used to generate the examples. So it won't get out of sync).

If you migrate from using the globals version of ember-table to the ember-cli version, and have any trouble, I'd like to hear it so I can create a good migration guide. Send me an email or post here!

## Notes

* `ember-table-addon` can be installed with both `npm` and `bower`. If you install with `npm`, it will work as an ember-cli addon; if you install via `bower`, you will get the globals-based build.
* We preserve backwards compatibility by building to the `dist` folder using the scripts in the `packaging` folder. Ember CLI builds are put in `ember-dist`.
  * To build the globals files, use `grunt dist`.
* As you test out this pre-release version in your apps, I'll be cleaning up the `README`, `CONTRIBUTING` and other docs. Then I'll open a pull request against `ember-table`, and transplant the `ember-table-addon` code in as a huge single commit. Previous ember-table commits and versions will still exist, but `ember-table-addon` files will replace old `ember-table` files.

**Comment by azirbel** [comment]
Actually, I broke backwards-compatibility for styling. I think I'm ok with that, but would like to hear opinions.

Previously, we exported our "financial table" CSS theme along with the ember-table CSS you get by default.

In this version, I've refactored the theme into https://github.com/Addepar/ember-table-addon/tree/master/addon/styles/themes. You can still import it if you want (LESS required), but it's not included in the default CSS. I think this is the correct behavior; in general, we need to do some work to make the "vanilla" ember-table as lightweight as possible.

To use the financial theme:

```less
// In your app's LESS file
@import '../vendor/ember-table/addon/styles/themes/financial.less';
```

Maybe we can add a build step to bundle the theme for those that want it. Let me know if you want this.

**Comment by cwiese** [comment]
“Financial table” is a major selling point to the whole customizable ember-table! 

Thanks!

**Comment by azirbel** [comment]
I decided to add back the financial theme for now. The goal is to make this upgrade as painless as possible (for globals users, just bumping the version number and no other changes).

As part of a later (breaking) release, we will remove the financial theme. This will be an easy upgrade on its own.

New commit to `ember-table-addon` master makes this change: https://github.com/Addepar/ember-table-addon/commit/1c9d53488f452eb73b4f46742ee16c911f65e0c8.

**Comment by intuitivepixel** [comment]
woot :+1: I'll give it soon a real drive ...

**Comment by igorT** [comment]
@jrhe might be interested

**Comment by testen** [comment]
I'm getting this error when I try to install it through ember command:

The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.

**Comment by azirbel** [comment]
thanks for the comment @testen! I saw that myself the other day, will look into it very soon.

**Comment by azirbel** [comment]
I've found one potential problem/breaking change for globals-users: isolated unit tests may break.

Previously, Ember Table used globals for everything internally - e.g. `{{view Ember.Table.BodyTableContainer}}`. Now we've switched it to use string names, like `{{view 'body-table-container'}}`.

Globals-based host apps don't know how to look up these new views so we've added an `initialize` step to the globals build. When you include Ember Table in your app, it will register its component and views on your app's container. See https://github.com/Addepar/ember-table-addon/blob/master/dist/ember-table.js#L2208.

This method may break unit tests: isolated unit tests have their own container, which needs to be told about these new views.

To fix this in our app, we had to add all Ember Table views to the test's `needs` property. We then had to change the resolver used by the tests, so that it would defer to the application container to look up these views. The code looks like this:

```
var customResolver = Ember.DefaultResolver.extend({
  resolveOther: function(parsedName) {
    var ret = this._super(parsedName);
    if (ret) { return ret; }
    return App.__container__.resolve(parsedName.fullName);
  }
});
setResolver(customResolver.create());
```

There doesn't seem to be a good way around this problem; we can't continue to use globals in view helpers, because the module structure doesn't support that. This only affects users who use globals and do isolated unit testing. I'll add this potential problem to the migration guide.

**Comment by testen** [comment]
I don't know if this is a silly question because I've started very recently to work with ember but with ember-cli-ember-table, I was able to import `table-cell` from `view` to customize the cells of a column. With this addon it doesn't seem to work (I suppose it's because `table-cell` isn't anymore in addon/views but app/views can't be access either). How can I import it to work with it?

**Comment by HenryVonfire** [comment]
By the way, in the example that @azirbel has provided (http://emberjs.jsbin.com/wedahatixe/1) the horizontal scroll doesn't move the headers of the columns.

**Comment by azirbel** [comment]
@HenryVonfire looks like ember-cli 0.2.3 doesn't want to install a package with a mismatched name (here, `ember-table` vs. `Addepar/ember-table`). Instead, use:

```
npm install --save-dev Addepar/ember-table-addon
ember g ember-table
```

I'll update the instructions above. Thanks for the find! Looking into your other comments now.

**Comment by azirbel** [comment]
@HenryVonfire - huge thanks for your comments. All the issues you brought up were major concerns.

The views weren't available because we'd put them in the `app` folder. I've moved them to the `addon` folder and imported/exported them in the `app` folder. Overriding views should work now with the latest commit to `ember-table-addon`.

I also fixed the horizontal scroll issue; in translating the code to JS I made a typo which created the bug.

Better JS Bin: http://emberjs.jsbin.com/zogiluveti/1/edit

If you find anything else, please let me know!

**Comment by HenryVonfire** [comment]
@azirbel you are wellcome :) there is some strange behaviour with reordering columns. In the examples you have provided, if you try to switch column2 for column1 dragging from the left side of the headercell it works, but if you do it from the right side of the headercell it doesn't work.

By the way, thanks for your effort solving these problems :)

**Comment by marcemira** [comment]
@azirbel isn't the example above using old emberjs, handlebars?
```javascript
<script src="//cdnjs.cloudflare.com/ajax/libs/handlebars.js/1.3.0/handlebars.js"></script>
<script src="http://builds.emberjs.com/tags/v1.4.0/ember.js"></script>
```

**Comment by azirbel** [comment]
@HenryVonfire that dragging issue has existed for a long time. Fixes are certainly welcome in either old or new versions of Ember Table!

@marcemira yes! Theoretically, there's no reason we need to require a new version of Ember. The build I'm producing now should work with 1.4 through 1.8. After 1.8 we have problems due to template compilation changing, so we will have separate branches for 1.9, 1.10, and 1.11.

At some point (undecided when), we will start merging those branches in and will stop supporting older versions of Ember.

**Comment by azirbel** [comment]
@HenryVonfire we're working on a fix for the column reordering issue. See https://github.com/Addepar/ember-table/pull/306

**Comment by HenryVonfire** [comment]
@azirbel It's good to hear that you are working on it. I'll try to see if I can do something :)

Also, I've found something else that I think it could be a bug. For some reason the width of the columns don't change. In your example columnWidth is set to 150 for Date and 100 for the rest of the columns but all of them have a size of 150. I've tried setting minWidth, defaultColumnWidth, columnWidth and maxWidth to values lower than 150 but none of them seem able to modify it.

**Comment by azirbel** [comment]
Ah, my example seems to be out of date. Try `savedWidth` - the documentation at http://addepar.github.io/ember-table/#/ember-table/documentation is correct.

**Comment by HenryVonfire** [comment]
I was following this documentation http://addepar.github.io/#/ember-table/documentation (don't ask me how I got to that url instead of yours)

**Comment by glennfu** [comment]
I'm currently using ember-cli 0.2.3 and ember 1.10.0. In my Bower.json I've been using `"ember-table": "https://github.com/Addepar/ember-table.git#ember-1.10"` and referencing things globally and it's been working great.

I first tried changing to the Bower dependency you suggested, but while it changed the contents of my bower_components/ember-table folder, there were no dist files to reference so I couldn't get that to work.

I instead removed the Bower dependency and tried the ember-cli way since I'm already using ember-cli. I was getting errors popping up reminding me I still hadn't replaced all of my global Ember.Table references. Once I got the last one fixed, I hit refresh in Firefox, and... beachball! I can't get the page to load past the controller's loading template. I tried in Chrome, same effect. It was even resistant to force-quit. If I comment out my ember-table component in my template, the page loads fine. I have no idea how to debug this!

**Comment by jrhe** [comment]
Try building up a table and its options bit by bit. Start with the minimal
set of options and then add options back one by one to see if it's a
problem with the table or one of the options. I had this problem earlier
when implementing keyboard selection. Can't remember what option was
breaking it though...

On Tuesday, April 28, 2015, Glenn Sidney <notifications@github.com> wrote:

> I'm currently using ember-cli 0.2.3 and ember 1.10.0. In my Bower.json
> I've been using "ember-table": "
> https://github.com/Addepar/ember-table.git#ember-1.10" and referencing
> things globally and it's been working great.
>
> I first tried changing to the Bower dependency you suggested, but while it
> changed the contents of my bower_components/ember-table folder, there were
> no dist files to reference so I couldn't get that to work.
>
> I instead removed the Bower dependency and tried the ember-cli way since
> I'm already using ember-cli. I was getting errors popping up reminding me I
> still hadn't replaced all of my global Ember.Table references. Once I got
> the last one fixed, I hit refresh in Firefox, and... beachball! I can't get
> the page to load past the controller's loading template. I tried in Chrome,
> same effect. It was even resistant to force-quit. If I comment out my
> ember-table component in my template, the page loads fine. I have no idea
> how to debug this!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Addepar/ember-table/issues/300#issuecomment-97161900>.
>


-- 
Sent from Gmail Mobile

**Comment by azirbel** [comment]
@glennfu: darn, too bad to hear about the ember-cli version not working out! I'm afraid I don't know why - if you're able to figure it out, I'd definitely like to know. I've been able to build simple examples in the new ember-cli style; probably starting from a smaller example and building up to a complex one is indeed the way to go.

Regarding the globals build: I'm surprised there were no dist files to reference. Are you sure you're pulling in the right version? Dist files are here: https://github.com/Addepar/ember-table-addon/tree/master/dist, same as in the old structure.

That said, you will have problems with those dist files because they are compiled for Ember 1.8 and the template compliation process has changed in 1.10. So making it work for you will involve applying the changes on the `ember-1.10` branch (here) to the ember-table-addon repository. Sorry about this, but I just don't have the time to make `ember-1.9` and `ember-1.10` branches for `ember-table-addon` yet.

**Comment by glennfu** [comment]
I'll carve out some time to try to drill down and figure out why it's freezing the browser.

As for the /dist stuff, my Bower.json has `"ember-table": "Addepar/ember-table-addon"` and this is what bower_components/ember-table looks like after a `bower install`:

![screen shot 2015-04-28 at 2 03 05 pm](https://cloud.githubusercontent.com/assets/20549/7377944/62f0950c-edaf-11e4-90b1-fa8705f82d31.png)

When my Bower.json has `"ember-table": "https://github.com/Addepar/ember-table.git#ember-1.10"`, my bower_components/ember-table looks like this:

![screen shot 2015-04-28 at 2 06 40 pm](https://cloud.githubusercontent.com/assets/20549/7377988/cfb3b8a4-edaf-11e4-958d-3ddefabef4e4.png)

As for your last point, no apology needed there. I was just trying to help regression test. I'm going to stick with my ember-1.10 branch until the ember-cli version is ready and then switch to that. I was explicit about which branch I'm on because I wasn't even sure you intended a migration to happen for that but thought I'd share anyway in case it helps!

**Comment by glennfu** [comment]
I tracked down the browser freeze to `canAutoResize: true` in my column definitions. Changing that to false removes the freeze. I even simplified it as far as I could with just a single column where the only thing displayed is the models' id, and `canAutoResize` will still lock up my browser.

Let me know if there's anything else I can do to help add more info!

**Comment by azirbel** [comment]
@glennfu, thank you so much for narrowing down the problem!

Even so, I'm afraid I'm not able to reproduce it: I made a new Ember-CLI app (Ember 2.3), installed `ember-table-addon`, and made a simple table much like on the docs pages. I set `canAutoResize: true` on all the columns and the behavior seemed fine.

Everything also works as expected at http://addepar.github.io/ember-table-addon/#/configurable-columns, which uses the new version.

It's possible that something about your setup is causing Ember Table to get stuck in its update-column-width calculation ([doForceFillColumns](https://github.com/Addepar/ember-table-addon/blob/master/addon/components/ember-table.js#L275)). If you're able to figure out what's going on, I'll be very interested to hear it; sorry that I can't help further.

Regarding the `dist` issue: does the same happen when you specify the hash of the ember-table version in `bower.json`? Like:

```
"ember-table": "Addepar/ember-table-addon#a30055d808220652a6545c5e8b1a7a923a111baf"
```

**Comment by ldevalliere** [comment]
+1 running into this issue too, also tracked it down to canAutoResize: true.

**Comment by glennfu** [comment]
I believe what's happening is if you're at a container width less than the sum of the minWidths, or perhaps near enough to it, this calculation: `newWidth = Math.floor((column.get('width') / totalResizableWidth) * availableWidth);` picks a size, and on the next step, `availableWidth` is a negative number. Once it's a negative number, it will get stuck in an infinite loop. I'll see if I can take a deeper look to find an actual solution.

I'm still not entirely sure how to describe the problem accurately, because I CAN set it such that the sum of the minWidths will indeed fit, and it still gets stuck. I'll keep tinkering.

**Comment by glennfu** [comment]
Here's how you can reproduce the issue @azirbel 

![screen shot 2015-04-29 at 12 19 52 pm](https://cloud.githubusercontent.com/assets/20549/7396871/2ecc4c24-ee6a-11e4-9f06-473293c1749c.png)

Plug in those numbers and hit Refresh Table.

**Comment by azirbel** [comment]
Thanks @glennfu! That sounds like plenty to go on - I'll fix it as soon as I can.

**Comment by azirbel** [comment]
@glennfu @ldevalliere - fixed on master. Huge thanks for the report! Looks like in my conversion to JS, a critical line of code got lost (not sure how; that's a bit troubling).

**Comment by ldevalliere** [comment]
@azirbel awesome, thank you!

**Comment by HenryVonfire** [comment]
I'm getting this exception:

`Typeerror: Cannot read property 'filterProperty' of undefined`

from the line 275:

`var columnsToResize = allColumns.filterProperty('canAutoResize');`

of `ember-table.js` when I try to use the ember-table inside a component instead of directly using it in a controller. It seems that the previous line `var allColumns = this.get('columns');` is returning undefined. I'm not sure if it's a bug (maybe I'm missing something when creating the component) but, since this is related to `canAutoSize` inside of `doForceFillColumns`, I leave it here.

Here is the code that is throwing the exception:
https://github.com/HenryVonfire/tables/blob/master/app/components/custom-table.js 

Also with the actual addon it tries to get `ember-table.css.map` from `assets/` without success.

**Comment by azirbel** [comment]
@HenryVonfire if you are extending `tableComponent`, you need to override the `columns` property. Yours is called `tableColumns` (the name I use in the examples, which gets bound to `columns` in the template).

**Comment by azirbel** [comment]
I've opened a PR: https://github.com/Addepar/ember-table/pull/309.

**Comment by HenryVonfire** [comment]
Thanks @azirbel! I don't know if you are aware of this, but the installation through `ember install ember-table` doesn't work, it returns a `404 Not Found: ember-table`.

**Comment by Yoshi3003** [comment]
@azirbel Hi, I have come across your add-on and seem like it is very useful! I am new to Ember and chose to work with Ember-CLI (0.2.3), and have followed through this issue. I have followed through your installation commands.
A few issues I have encountered when trying to initialize things following your updated-cli-style DEMO at the url: http://addepar.github.io/ember-table-addon/#/simple
1. The template: 
{{ember-table hasFooter=false columns=tableColumns content=tableContent}}
uses deprecated binding style attributes shown in my dev console 'WARNING: Binding style attributes may introduce cross-site scripting vulnerabilities; please ensure that values being bound are properly escaped.' 

2. In-line styling in the generated ember table elements. Should I be concerned? 
3. As @HenryVonfire mentioned previously, I have also encountered 'http://localhost:4200/assets/ember-table.css.map 404 (Not Found)' error.

Thank you!

**Comment by jrhe** [comment]
@Yoshi3003 points 1 and 2 are addressed in a pull request in ember-table-addon. They aren't particularly concerning, it happens to anything which puts a value into a style tag without escaping it in ember 1.11 upwards http://emberjs.com/deprecations/v1.x/#toc_warning-when-binding-style-attributes.

The 404 you are mentioning is different to that that @HenryVonfire is getting, his is for the ember table source code, yours is for the source map. The source map not being available doesn't  impair the use of the addon, it just means its harder to debug as the lines in the compiled dist files wont get mapped back to the original source.

**Comment by HenryVonfire** [comment]
@jrhe maybe @Yoshi3003 is referring not to my last comment:
> the installation through ember install ember-table doesn't work, it returns a 404 Not Found: ember-table

but my previous one:

> Also with the actual addon it tries to get ember-table.css.map from assets/ without success.

**Comment by Yoshi3003** [comment]
@HenryVonfire @jrhe Thank you for your clarifications. I have included contentSecurityPolicy settings in config/environment.js and the warnings seem to go away. 

However, when I have included 'ember-table' in my template and defined the tableColumns and tableContent functions in my controller (as in the DEMO), the rendered table's height appears to be 2px, after checking its css styles. It appears it's overriden by some logic and not used the styling in the css (chrome dev console shows height to be from element.style instead of from the one defined in vendor.css). I guess I must be doing something stupidly wrong here...

**Comment by azirbel** [comment]
@Yoshi3003 does it work if you put the table in a containing div with a fixed height?

**Comment by Yoshi3003** [comment]
@azirbel It seems to do the trick. I enclosed the table with a div and specified height to be some arbitrary values. Thank you!

**Comment by azirbel** [comment]
The Ember-cli PR is merged! Thanks for your help everyone!
