### ISSUE TITLE
Scollbar issue

### ISSUE THREAD

**Issue by svkangal** [Addepar/ember-table#301]
Imagine the ember table taking up 100% width of the page and is rendered at the bottom of the page. 
Right now the table scrolling works fine inside the table, but once the scrollbar reaches top the rows the page doesn't scroll and the view is stuck in the table.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
