### ISSUE TITLE
New community example: rowclick example (ember-cli version)

### ISSUE THREAD

**Issue by hlogmans** [Addepar/ember-table#302]
I have created a gist for the new cli-version that uses some functionality that is not trivial from the docs:
- clicking a row transitions to a route
- sorting is done outside of the table, but the table updates if sorting field is altered.
- handling a footer row with content

https://gist.github.com/hlogmans/7e49740e2fc87d7d4e07

Thanks for the great table functionality.

**Comment by azirbel** [comment]
This is great @hlogmans - thank you! I'll wait until I merge the new cli version, but will add it to the examples list then.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
