### ISSUE TITLE
Ember 1.12

### ISSUE THREAD

**Issue by sshillo** [Addepar/ember-table#310]
I created a branch on my fork that bumps the ember version so I can use this with ember 1.12, thought it would be useful for others. I don't think I can send a pr since this branch doesn't exist yet on the master repo, https://github.com/sshillo/ember-table/tree/ember-1.12

**Comment by azirbel** [comment]
After seeing https://github.com/Addepar/ember-table/pull/316 I set up an `ember-1.12` branch. Hopefully that works for you! If not, I'll be happy to accept PRs into that branch now.
