### ISSUE TITLE
Rename sortByColumn action to columnClicked action

### ISSUE THREAD

**Issue by drglitch** [Addepar/ember-table#313]
This is likely related to conversations in https://github.com/Addepar/ember-table/pull/186 and https://github.com/Addepar/ember-table/pull/184.

sortByColumn is sprinkled throughout the codebase in few spots - in treetable as well as header template, and is fired on click on the column header.

I propose renaming it to a more generic columnClicked (or similar) action name - this way various custom functionality can be implemented, including sort or (as described in #186 discussion) showing a menu or similar.

ideally, this should also support:
- modifier keys (CTRL/ALT)
- right click

Thoughts? :)

**Comment by igorT** [comment]
I think `columnHeaderClicked` might make more sense

**Comment by drglitch** [comment]
@igorT  good point lol

**Comment by drglitch** [comment]
After researching this further, it looks like modifier keys wont cut it because Ember's "action" handles the click event and does NOT send actual mouse event.

Instead, my workaround will be to listen to click or mousedown event on the view itself and act accordingly depending on modifier keys pressed (all of this is necessary for multicolulm sort support heh).

I think this should *not* be included in core code as its an edge usecase - i will provide community example if desired though.

As far as renaming sortByColumn to columnHeaderClicked, expect a pull req shortly

**Comment by drglitch** [comment]
For those who may come through here in future: use *click* event and not the *mouseDown* event because the latter may break column resize (resize starts with mouseDown)

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
