### ISSUE TITLE
ember install ember-table failed with Error: 404 Not Found: ember-table

### ISSUE THREAD

**Issue by tomarsamar** [Addepar/ember-table#315]
I am using ember-cli  0.2.5  but when I executed addon installation command, it failed with Error: 404 Not Found: ember-table
      I think that, moving to ember-cli is work in progress ( as readme file is edited few hours back) and may take some time before it reflect on NPM but I am not sure.
![command-centre-hq_ _bash_ _178x46](https://cloud.githubusercontent.com/assets/945326/7768576/3cfd5670-009a-11e5-907d-8915b27d5864.png)

**Comment by azirbel** [comment]
Yep, your guess is right. We should be publishing to npm tonight.

**Comment by azirbel** [comment]
We've published to NPM; the command should work now.

I made a simple demo app, in case anyone has trouble working with Ember Table and Ember CLI: https://github.com/azirbel/ember-table-demo.

**Comment by MichalBryxi** [comment]
💝 thank you!
