### ISSUE TITLE
Error with 'ember generate' and deprecations warnings on version 0.5.0

### ISSUE THREAD

**Issue by HenryVonfire** [Addepar/ember-table#321]
After reinstalling ember-table to its version 0.5.0 with `ember install ember-table` I get the following error:

> The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.

Which I think means that I should run this command: 

> `ember g ember-table`

After running this command the table works but all the deprecated warnings have returned.

Also, there is a folder called `.stage` inside the folder of ember-table that I haven't seen before.

**Comment by azirbel** [comment]
I can't reproduce this. What version of ember-cli are you using, and what does the `ember-table` entry in `package.json` look like?

The `.stage` is used for releases. It should only be created if you run `grunt release-it`, but in any case it's git-ignored (https://github.com/Addepar/ember-table/blob/master/.gitignore#L22) and you don't have to worry about it.

**Comment by HenryVonfire** [comment]
@azirbel it has happened to me with 2 different projects, one with `ember 1.12.0` and `ember-cli 0.2.5`, and another one with `ember 1.11.1` and `ember-cli 0.2.3`.

To be sure, today I've tried with this [project](https://github.com/HenryVonfire/tables). I deleted the previous reference to ember-table-addon in `package.json`, then I ran `npm install`, `bower install` and `ember install ember-table` at the end. After that I get that error but in `package.json` shows correctly `ember-table: "0.5.0"`. Could it be that I'm not cleaning correctly the previous version?

**Comment by cwiese** [comment]
happening for me too.... widthBinding deprecated.   I am using ember-cli 0.2.6 ember 1.12.0 - weird I removed the Ember-Table-Addon from bower-components - and bower.json ....

remove old ember-table from bower
rm -rf tmp
bower cache clean

I just discovered it is in the DIST/ember-table.js bit not in the source js files!!!

**Comment by HenryVonfire** [comment]
Some of the warnings about deprecations come from the new way of defining getters and setters in ember 1.12:
http://emberjs.com/deprecations/v1.x/#toc_computed-properties-with-a-shared-getter-and-setter

**Comment by cwiese** [comment]
Agreed, and I fixed mine.    However, the DIST/ember-table.js is still old in when I installed from NPM.

I am having issues building it to.

>> Error: Invalid tree found. You must supply a path or an object with a `read` function.

Ugh.

**Comment by cwiese** [comment]
Okay ... got the DIST/ember-table.js to rebuild using a clone not npm version.   However, they are still there
 app/templates/table-row.hbs 
{{view "multi-item-collection" rowBinding="view.row"  contentBinding="view.columns"}}

These warning slow the table down a bunch in development (I have 1000's of warnings).  

Will this work?  row="view.row (in stead of this: rowBinding="view.row")

**Comment by HenryVonfire** [comment]
@cwiese you can make the same changes they did with [ember-table-addon](https://github.com/Addepar/ember-table-addon) to remove the warnings.

You need to do 2 things:
First, change in `templates/table-row.hbs` and `templates/header-row.hbs` any `xBinding="var"` for `x=var`. 

Second, replace your addon/mixin/style-bindings.js for [this one](https://github.com/Addepar/ember-table-addon/blob/master/addon/mixins/style-bindings.js).

That worked for me. I don't know the reason why these changes haven't been made in the official ember-table. I hope @azirbel give us more information when he can :)

**Comment by cwiese** [comment]
Thank you Henry - I was just testing the Binding removal.  Should we do a PR?

**Comment by HenryVonfire** [comment]
@cwiese since getting ride of this warnings improve the performance of the table, I think we should :)

**Comment by cwiese** [comment]
@HenryVonfire  Thank you for the insight.
I am having quite an issue making the StyleBindings HtmlSafe.  This does not seem to work  `styleString.htmlSafe();`

```javascript
  exports['default'] = Ember['default'].Mixin.create({
    concatenatedProperties: ['styleBindings'],
    attributeBindings: ['style'],
    unitType: 'px',
    createStyleString: function(styleName, property) {
      var value;
      value = this.get(property);
      if (Ember['default'].isNone(value)) {
        return;
      }
      if (Ember['default'].typeOf(value) === 'number') {
        value = value + this.get('unitType');
      }
      return Ember['default'].String.dasherize("" + styleName) + ":" + value + ";";
    },
    applyStyleBindings: Ember['default'].on('init',
      Ember['default'].observer('styleBindings', function() {
      var lookup, properties, styleBindings, styleComputed, styles,
        _this = this;
      styleBindings = this.get('styleBindings');
      if (!styleBindings) {
        return;
      }
      lookup = {};
      styleBindings.forEach(function(binding) {
        var property, style, tmp;
        tmp = binding.split(':');
        property = tmp[0];
        style = tmp[1];
        lookup[style || property] = property;
      });
      styles = Ember['default'].keys(lookup);
      properties = styles.map(function(style) {
        return lookup[style];
      });
      styleComputed = Ember['default'].computed(function() {
        var styleString, styleTokens;
        styleTokens = styles.map(function(style) {
          return _this.createStyleString(style, lookup[style]);
        });
        styleString = styleTokens.join('');
        if (styleString.length !== 0) {
          //caw
          return styleString.htmlSafe();
        }
      });
      styleComputed.property.apply(styleComputed, properties);
      return Ember['default'].defineProperty(this, 'style', styleComputed);
    }))
  });

});

```

**Comment by HenryVonfire** [comment]
@cwiese I don't remember who suggested it but calling ´toString()´ at the end does the job:
´styleString.htmlSafe().toString()´

**Comment by cwiese** [comment]
I tried that too.  In fact, I copied the exact file from the add-on.  Apparently, something has changed in - it fails this warning test

‘‘‘javascript
AttrNode.prototype._deprecateEscapedStyle = function AttrNode_deprecateEscapedStyle(value) {
    Ember['default'].warn(
      styleWarning,
      (function(name, value, escaped) {
        // SafeString
        if (value && value.toHTML) {
          return true;
        }
‘‘‘

**Comment by HenryVonfire** [comment]
@cwiese that's strange because it works for me doing exactly the same. Have you changed something else?

**Comment by Yoshi3003** [comment]
@HenryVonfire I'm currently new to EmberCLI. I recently also changed from Ember-table-addon to Ember-table 0.5.0 and encountered deprecation warnings as you said earlier. I followed your steps of:

You need to do 2 things:
First, change in templates/table-row.hbs and templates/header-row.hbs any xBinding="var" for x=var.
Second, replace your addon/mixin/style-bindings.js for this one.

How do 'apply' the changes to the add-on ? I tried restarting the server but I still encountered the deprecation warnings. Sorry I am new to EmberCli.

Thank you.

**Comment by HenryVonfire** [comment]
@Yoshi3003 I'm fairly new to EmberCLI too, so maybe I won't be of too much help for you. For me, just running again `ember serve` is enough to apply the changes. 

I suggest you to clone/download ember-table project, make the changes there and see if you get the same warnings. If not, they are coming from something else in your project. Also keep in mind which version are you using of EmberCLI and Ember, maybe you are using one too old or the newest one are not suitable yet to be used with ember-table.

**Comment by cwiese** [comment]
You need to run "grint dist" from the ember-table add-on folder.   Also, I used Financial Table - there are additional issues with that table.

**Comment by Yoshi3003** [comment]
@HenryVonfire Okay sorry I verified that it actually applied the changes when doing ember serve. However like @cwiese said, I copied the style-bindings.js from there and still got warnings.

However, when I tried to change ```return styleString.htmlSafe().toString();``` to ```return styleString.htmlSafe();```, the warnings went away. @cwiese Hope this will help you.

My embercli versions are: 
embercli: 0.2.7
ember: 1.11.1

**Comment by cwiese** [comment]
Yes, I used styleString.htmlSafe()  also.  Thanks! Now I need to tackle the Financial Table warnings!

**Comment by jrhe** [comment]
@azirbel It seems that some versions of ember need htmlSafe().toString() and others need just htmlSafe(). What do you think the best way of tackling this is? Conditional which checks the ember version?

@HenryVonfire What version of ember were you using when adding .toString() fixed the deprecation warning? I added it to ember-table-addon as it solved my problem but now I have had to revert to just htmlSafe().

**Comment by HenryVonfire** [comment]
@jrhe I don't remember in which version I needed it. I think at first I was working with ember-cli 2.3 and ember 1.11 but now with ember-cli 2.5 and ember 1.12 I'm using only htmlSafe().

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
