### ISSUE TITLE
CSP inline errors

### ISSUE THREAD

**Issue by jonathanKingston** [Addepar/ember-table#324]
Avoiding the antiscroll issues there are issues with the style bindings, I'm not immediately sure if Ember can modify the dom without using `style=""` attributes however the following code does the same thing:

```
(function () {


var native = HTMLElement.prototype.setAttribute;

HTMLElement.prototype.setAttribute = function (attr, value) {
    if (attr === 'style') {
      resetStyles(this);
      applyStyles(this, value);
    } else {
      native.apply(this, arguments);
    }
  };

  function applyStyles(element, styleString) {
    var styles = styleString.split(';');
    styles.forEach(function (styleBit) {
      var parts = styleBit.split(':');
      var property, value;
      if (parts.length === 2) {
        property = parts[0].trim();
        value = parts[1].trim();

        element.style[property] = value;
      }
    });
  }

  function resetStyles(element) {
    var styleList = [].slice.call(element);
    styleList.forEach(function (propertyName) {
      element.style.removeProperty(propertyName);
    });
  }

}());
```

I'll be releasing this as a plugin soon however it's a massive hack so I am raising this issue so we can track finding a better solution.

**Comment by jonathanKingston** [comment]
Antiscroll issue that isn't fixed by this (however impacts ember-table):
https://github.com/azirbel/antiscroll/pull/1

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
