### ISSUE TITLE
Cell merging.

### ISSUE THREAD

**Issue by RomanPerin** [Addepar/ember-table#326]
Hi!

Is it possible to merge table cells?
I want to have a table that contains 2 different types of rows. First type of rows must have 5 cells (1 cell per 1 column). And Second type of rows must have 2 cells (1 cell per 2 columns and 1 cell per 3 columns).
So, is it possible to customize table in this way?

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
