### ISSUE TITLE
Table limited to ~1,118,480 rows max due to AntiScroll and browser limits

### ISSUE THREAD

**Issue by drglitch** [Addepar/ember-table#327]
Currently, Ember Table is limited to displaying 1,118,480 rows of data due to its use of antiscroll.js. This happens because internally antiscroll uses a very large div (`#ember-table-table-scrollable-wrapper`) to keep track of the scroll offset. Unfortunately, browsers impose maximum height that a div can be (see below), making it physically impossible to scroll past ~1.1m rows.

This makes it impossible to use (virtual) data sources with more than 1.1m rows :)
- One available workaround is pagination, but this is not desirable/feasible in all cases.
- Another workaround is to decrease each row height, giving you few extra K of rows.

This issue is caused by the internal implementation of antiscroll and is likely directly related to #261.

It would be great to remove this limitation, and i am thinking about options for doing so...
One thought is to implement a custom scroll-bar with minimum height that would calculate offset/1px weight based on row count and height of each row (in this scenario, each row would be expected to be of identical height).

Either way, what are your opinions on getting something like this to work smoothly with existing codebase? It would be great to isolate the renderer enough to make it replaceable-in-place.

Maximum div height discussion: http://stackoverflow.com/questions/16637530/whats-the-maximum-pixel-value-of-css-width-and-height-properties

Firefox: 33,554,400px
Chrome:  33,554,428px
Opera:   33,554,428px
IE 9:    21,474,836.47px

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
