### ISSUE TITLE
Custom cells for footers

### ISSUE THREAD

**Issue by HenryVonfire** [Addepar/ember-table#330]
Looking at the code of ember-table, I've realized that the footer behaves like the body rows with the only difference of being a static one at the end of the table. I was wondering how could I give it the possibility of having custom cells like the header and the body cells do. This are the changes that I think I should implement to be able to specify the custom view in the column definition:
- [addon/components/ember-table.js] add the next lines:
  `footerRowView: 'footer-row',`
  `footerRowViewClass: Ember.computed.alias('footerRowView'),`
- [addon/model/column-definition.js] add the next lines:
  `footerCellView: 'footer-cell',`
  `footerCellViewClass: Ember.computed.alias('footerCellView'),`
- [addon/views/table-block.js] 
  duplicate and rename for `footer-block.js`
  change in footer-block.js `itemViewClass:  Ember.computed.alias('tableComponent.tableRowViewClass'),` for `itemViewClass: Ember.computed.alias('footerComponent.tableRowViewClass'),`
- [addon/views/table-row.js] 
  duplicate and rename for `footer-row.js`
  change in `footer-row.js` `templateName:'table-row'` for `templateName:'footer-row'`
- [app/template/table-row.hbs] 
  duplicate and rename for `footer-row.hbs`
  change in `table-row.hbs` `itemViewClassField="tableCellViewClass"` for `itemViewClassField="footerCellViewClass"`

is this the right approach? Am I missing something else?

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
