### ISSUE TITLE
Issue with fixed columns over half of the table

### ISSUE THREAD

**Issue by HenryVonfire** [Addepar/ember-table#334]
When the number of fixed columns are bigger than half of the table it starts to work weird (for example not rendering borders or overlapping columns). It can be tested with the jsbin example too:

http://emberjs.jsbin.com/gecikanayu/1/edit

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
