### ISSUE TITLE
  Issue with fixed columns and reorder

### ISSUE THREAD

**Issue by HenryVonfire** [Addepar/ember-table#336]
For example, in a table of 3 or more columns, when 2 of them are fixed and you want to switch their positions, if you pick first the one on the left, this goes at the end of the table and the third column gets in the second position, inside the group of the fixed columns. It doesn't work either when the second one tries to switch positions with the first one.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
