### ISSUE TITLE
Issue adding a checkbox in ember table

### ISSUE THREAD

**Issue by srsh144** [Addepar/ember-table#343]
Hi, 
I am trying to add a checkbox in each row of the table. It works fine when there is no scrolling required. But the issue arises as the rows are more enough, with a scrolling enabled. While selecting a checkbox in a particular row, the row which is out of the scope and not visible gets selected. 
Lets say there are 10 rows in total and visible rows are first 5. When i select the 2nd row's checkbox , 7th row's checkbox automatically gets selected. 

Hope i am clear enough about the problem.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
