### ISSUE TITLE
Refactor to use list-view for potential performance improvements

### ISSUE THREAD

**Issue by go1dfish** [Addepar/ember-table#35]
Basing ember-table on ListView would likely help improve scrolling performance and centralize optimization efforts rather than duplicating efforts

https://github.com/emberjs/list-view

Functionality it seems similar to the LazyContainer(Item)View's currently used by ember-table

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
