### ISSUE TITLE
wrong entities encoding on project's homepage

### ISSUE THREAD

**Issue by gitowiec** [Addepar/ember-table#355]
Hi, I am new to ember-table, just reading and trying its code. On documentation page I can see coded entities, please correct it because it is unusable.
Browse:Chrome ( 43.0.2357.132 m (64-bit)) sys: M$ Windoze 7
http://addepar.github.io/ember-table/#/simple

![capture](https://cloud.githubusercontent.com/assets/1553195/8712239/1e5e78c6-2b5a-11e5-8263-2b32a77e7be2.PNG)

**Comment by azirbel** [comment]
Thanks for reporting this, @gitowiec! It should be fixed very soon with this PR: https://github.com/Addepar/ember-table/pull/349.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
