### ISSUE TITLE
Consider/experiment with use supergroup.js for data mangling

### ISSUE THREAD

**Issue by taras** [Addepar/ember-table#356]
Preparing data for presentation in the browser can be a real mess. On most projects that I've worked with, we usually start off with doing that in the browser and later moving it into the API. This simplifies the frontend code and makes everything much simpler to think about. But often, data mangling in the browser is unavoidable, especially for tables like the Financial Table Example.

It would be great if we had a standard way of preparing data to be presented in the table. For this purpose, we might want to look at using something like [supergroup.js](https://github.com/Sigfried/supergroup) which is designed for this purpose. 

Toptal has an article about [Ultimate In-memory Data Collection Manipulation with Supergroup.js](http://www.toptal.com/javascript/ultimate-in-memory-data-collection-manipulation-with-supergroup-js)

What are you thoughts about this?

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
