### ISSUE TITLE
how to use ember-table with ember-data

### ISSUE THREAD

**Issue by gitowiec** [Addepar/ember-table#367]
Hi
I would like to adapt [Ajax example](http://addepar.github.io/ember-table/#/ajax) to use Ember Data. What I tried is to extend Ember.ArrayProxy same way as in `ajax-table-lazy-data-source.js` and make an instance of it using response from the DS.Store.find().
In the response I have meta {total:150}, which I am using to fill empty spaces in Em.ArrayProxy.content.
The problem is that paths in columns of ember-table component configuration are not working.
For using with DS.AdapterPopulatedRecordArray this is good
`
        {
            savedWidth: 250, headerCellName: 'Question, contentPath: 'questionText'
        },
`
But when I do Em.ArrayProxy.create(DS.AdapterPopulatedRecordArray instance) it doesnt work any more (have to change `contentPath: 'questionText'` to `contentPath: '_data.questionText'`). This change is a bit weird, and I don't know if it is proper way to do it. I would like to override DS.AdapterPopulatedRecordArray but as I checked in Ember Data source code use of DS.AdapterPopulatedRecordArray class is hardcoded.

Any help would be appreciated, best regards.

**Comment by josiahbryan** [comment]
@gitowiec  - Did you ever end up getting ember-table with ember-data to work? I just discovered this project (nearly two years later!) and was thinking of the same thing myself! Any how-to or lessons learned would be greatly apprecated.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
