### ISSUE TITLE
Error installing 0.9.1

### ISSUE THREAD

**Issue by morten-holm** [Addepar/ember-table#369]
Hi 

I'm having trouble installing ember-table 0.9.1:

ember install ember-table@0.9.1
version: 1.13.6
Installed packages for tooling via npm.
installing ember-table
Installing browser packages via Bower...
  not-cached git://github.com/Addepar/antiscroll.git#e0d1538cf4f3fd61c5bedd6168df86d651f125da=git://github.com/Addepar/antiscroll.git#e0d1538cf4f3fd61c5bedd6168df86d651f125da
  cached git://github.com/jquery/jquery-mousewheel.git#3.1.13
  cached git://github.com/components/jqueryui.git#1.11.4
Tag/branch e0d1538cf4f3fd61c5bedd6168df86d651f125da=git://github.com/Addepar/antiscroll.git#e0d1538cf4f3fd61c5bedd6168df86d651f125da does not exist
Error: Tag/branch e0d1538cf4f3fd61c5bedd6168df86d651f125da=git://github.com/Addepar/antiscroll.git#e0d1538cf4f3fd61c5bedd6168df86d651f125da does not exist
...

Ember version: ember -v
version: 1.13.6
node: 0.12.4
npm: 2.13.2
os: darwin x64

**Comment by azirbel** [comment]
Sorry to hear! We've run into this kind of problem before: when you install ember-table, it tries to install https://github.com/Addepar/antiscroll as a Bower dependency. For some reason, it can't find commit `e0d1538cf4f3fd61c5bedd6168df86d651f125da` (even though I can see that it exists at https://github.com/Addepar/antiscroll/commit/e0d1538cf4f3fd61c5bedd6168df86d651f125da).

What is the result of running the following two commands?

```
bower install git://github.com/Addepar/antiscroll.git#e0d1538cf4f3fd61c5bedd6168df86d651f125da

bower install https://github.com/Addepar/antiscroll.git#e0d1538cf4f3fd61c5bedd6168df86d651f125da
```

**Comment by morten-holm** [comment]
Both of the above commands executes just fine - still can't install ember-table though (same error).
