### ISSUE TITLE
_height and flexbox

### ISSUE THREAD

**Issue by QuinnLee** [Addepar/ember-table#373]
I am using the table inside a flex-container.  The `_height` attribute was set to the height of the body, and the vertical scroll bar wouldn't be created.

I added `this.set('_height', this.get('height'))` in the `didInsertElement` callback,  `_height` get set to `650` or whatever we set it to and the vertical scrolling is enabled.  I'm not sure if this is the right solution, just wanted to share it.

**Comment by LydiaBarnes** [comment]
We are currently looking into improving table behavior in flex layouts, will also look into this particular issue you found, thanks!

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
