### ISSUE TITLE
Uncaught Error: Property set failed: object in path "tableComponent" could not be found or was destroyed.

### ISSUE THREAD

**Issue by yonida** [Addepar/ember-table#375]
Using the addon in my project, I try to implement your Hello World demo, and get the following error:
`Uncaught Error: Property set failed: object in path "tableComponent" could not be found or was destroyed.`

Using "ember-cli": "1.13.1", "ember": "1.13.3"

Is it supported?

**Comment by mageshn28** [comment]
Right now Ember table support up to ember 1.12 only

**Comment by yonida** [comment]
Thanks @mageshn28 
Someone should write it in the README file. wasted my time for this..

**Comment by HenryVonfire** [comment]
@yonida there is a PR with a [version](https://github.com/Addepar/ember-table/pull/374) of the table compatible with ember 2.0

**Comment by yonida** [comment]
thanks. closing this for now.
