### ISSUE TITLE
Sort by column

### ISSUE THREAD

**Issue by fullofcaffeine** [Addepar/ember-table#376]
Hi!

Does ember-table support sorting by column - as in clicking in a specific column will sort by rows by the values of this specific column (using the data already loaded into it, no roundtrip to the server)?

Cheers,

Marcelo.

**Comment by moshemal** [comment]
http://addepar.github.io/ember-table/#/community-examples

**Comment by fullofcaffeine** [comment]
Hey, thanks. I was looking for clientside sorting, but that shouldn't be hard to implement. Right now, however, I can't even get it to work with Ember 2.0 :/

**Comment by fullofcaffeine** [comment]
https://github.com/Addepar/ember-table/issues/377
