### ISSUE TITLE
Not being able to get it to work

### ISSUE THREAD

**Issue by fullofcaffeine** [Addepar/ember-table#377]
Hi,

I'm not being able to render anything to `ember-table`. The initial value for the table should be empty, and ideally it would show the table with the header and footer, but blank content. However, right, now, it looks like this:

![screenshot 2015-09-10 23 17 10](https://cloud.githubusercontent.com/assets/81248/9807136/662630cc-5814-11e5-8c5f-ebe5edd2ad1a.png)

Its height is set to `2px` at the element level, for some reason:

![screenshot 2015-09-10 23 32 50](https://cloud.githubusercontent.com/assets/81248/9807137/6a2fa52c-5814-11e5-83cf-f0b94fe454cb.png)

Here's the markup I'm using for this specific `ember-table` (in Emblem):

```
 = ember-table hasHeader=true hasFooter=true numRows=100 columns=tableColumns content=tableContent
```

The format of the tableContent array is a simple array of objects (`[{Foo: 'foo', Foobar: 'foo', ...}, ...]`). I also have the column definitions in the controller, here's a sample:

```
  tableColumns: Ember.computed(function() {
    var foobar3Column = ColumnDefinition.create({
      textAlign: 'text-align-left',
      headerCellName: 'Foobar3',
      getCellContent: function(row) {
        //debugger
        return row.get('Foobar3');
      }
    });
    ...
   return [foobar3Column, ...];
```

(An interesting observation, see the commented-out debugger there? If I uncomment it and run everything, it just does not stops at this breakpoint. However, the columns *are* loaded (see screenshot below)... why?)

The initial value for `tableContent` is an empty array, in the controller:

```
 tableContent: [],
  ...
```

The user uses my form by filling the inputs one by one, and when a value is selected, a action called `submitForm` is sent to the controller. This action does a simple `$.getJSON` request to a HTTP API endpoint, and when the `promise` is resolved successfully, it then sets the `tableContent` property on the controller (which is bound to the `ember-table` `content` property, as shown in the markup above).

However, when the `tableContent` property is filled with the fetched data (the array of objects from the returned from the server), the table stays at its 2px height and doesn't update. If I manually increase the height, here's how it looks:

![screenshot 2015-09-10 23 36 48](https://cloud.githubusercontent.com/assets/81248/9807162/d5f0e456-5814-11e5-81fc-d8e4ac279a7a.png)

If I click inside the table, I get the following error:

```Uncaught TypeError: Cannot read property 'undefined' of undefined (ember-table.js:584)```

I just could not get it to work. I'm using `Ember CLI 1.13.6`, and `Ember-Table 0.9.2`. 

Any hints appreciated, I'm completely lost here :/

**Comment by HenryVonfire** [comment]
If you haven't done yet, you need to wrap the table in a div with a prefixed size (check the examples in test/dummy).

If you are using bootstrap, I had problem with it recently. In your `package.json` put your `"ember-table":"0.9.2"` before it.

**Comment by derekbrown** [comment]
@fullofcaffeine Were you able to get this resolved with @HenryVonfire's tip?

**Comment by spinlock99** [comment]
I'm just looking at `ember-table` for the first time as well and wrapping the table in a div did get it to show for me:

    <div style="height:3000px">
      {{ember-table hasFooter=false
                             columns=tableColumns
                             content=tableContent}}
    </div>

But, scrolling and resizing are broken. If I try to resize the columns I get a CSP error and the table disappears:

    [Report Only] Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-PGJ8tjuz2DXGgB1Sie9pW8BrxBGK6EQndbLEkXd44T8='), or a nonce ('nonce-...') is required to enable inline execution.

It is a `[Report Only]` violation so that might be a red herring.

Anyway, is this the normal learning curve with `ember-table`? I'm using Ember 1.13.7 which is after the memory leak fix that really broke views. Could that be the problem?

Thanks!

**Comment by cyril-sf** [comment]
Are you using @artych's PR? ( #374 )

Ember Table doesn't officially currently support Ember 1.13.

**Comment by DanChadwick** [comment]
I'm sure the CSP is a red herring. Use `'style-src': "'self' 'unsafe-inline'"` in the `contentSecurityPolicy` entry for your configuration in config/environment.js.

I've been using PR #374 very successfully with ember 2.0+. I'm learning ember, ember-data, ember-table and a bunch of other things, all concurrently. Very steep indeed.
