### ISSUE TITLE
scroll is not getting reset when Changing the model

### ISSUE THREAD

**Issue by GaneshKumaresan** [Addepar/ember-table#378]
I have implemented pagination concept in my ember-table. 

My scenario :-  
                     I scrolled to the last record of the table, and now I click the next page, the model is getting updated but the scroll is not getting reset. The scroll is still present in the last record of the new model. Kindly give me some advice regarding this. Thanks in advance.

**Comment by GaneshKumaresan** [comment]
Is there anyone faced this issue ??? Please let me know where i missed out.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
