### ISSUE TITLE
Tabbing between columns only move the content of the table

### ISSUE THREAD

**Issue by HenryVonfire** [Addepar/ember-table#379]
Maybe this table wasn't planned for this, but when using editable components in the cells and clicking Tab to move to the next cell, if the table is wide enough to have an horizontal scroll, then only the body of table moves. The header and the footer stay in the same position.

**Comment by HenryVonfire** [comment]
If anyone is interested in solve this issue, I've found this fairly easy solution:

Just adding an event on `keyDown` to detect when the tab has been pressed and then, scrolling the offset of the focused element:

```
keyDown(e) {
    if (e.which === 9) {
      const focus = this.$(':focus');
      const scrollLeft = focus[0].offsetLeft;
      this.$("div.antiscroll-inner").scrollLeft(scrollLeft);
    }
  }
```

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
