### ISSUE TITLE
Suggested Improvement

### ISSUE THREAD

**Issue by Me1000** [Addepar/ember-table#38]
As per: https://twitter.com/justindross/status/314774920955559936

I skimmed through the current issues and just decided to sum up my thoughts here in a single issue, then let you break them into sub issues or whatever if you choose to.

Keep in mind, as I write this, I feel like the tableview should behave as closely as possible to a native table component in desktop software.

The first thing I notice is that while scrolling framerate is fine, the actually displaying of the cells in the table is just slow. As you scroll it takes time before the newly exposed rows are displayed. In my blog post I gave an example of a list view that I wrote that has 60fps. It uses Cappuccino, but you should be able to get a good idea of what's going on. Cell reuse is pretty simple.

The next thing I noticed were the header cells. The cursor is for text selection, but when you drag to select text it reorders the column… or in the case of an actual data cell it either doesn't select anything or starts editing the cell. Now, the "tradition" web app might show a four arrow cursor or hand pointer thing, but on the desktop we just use a regular cursor, and it turns out the experience is much more "mature" than a four arrow cursor.
- The column sorting should have some kind of sort indicator… it's kind of disorienting.
- When I scroll quickly through one table it sometimes causes the web page itself to scroll (while I'm in the middle of the table).
- Editable cells should edit on a double click, not a single click. Also double clicking cell (to edit it) shouldn't deselect it.
- Clicking on the stars in the "Analyst Rating" column shouldn't select the row.
- The date picker is a nice touch, but using the arrow keys while it's being edited changes the row selection instead of moving the current selected date segment up/down.

Hope that helps a bit!
- Randy

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
