### ISSUE TITLE
Fixing the table columns from Right

### ISSUE THREAD

**Issue by newair** [Addepar/ember-table#380]
Hi,

I am attempting to fix columns from right. I did not find that feature and I tried to override the implementation using 

**tableColumns: Ember.computed(function() {
    var columns, numFixedColumns;
    columns = this.get('columns');
    if (!columns) {
      return Ember.A();
    }
    numFixedColumns = this.get('numFixedColumns') || 0;
    return columns.slice(0, columns.get('length')-numFixedColumns) || [];
  }).property('columns.@each', 'numFixedColumns')**

Which did not work. Any help will be really appreciated

Thank You !

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
