### ISSUE TITLE
Uncaught TypeError: Cannot read property 'rebuild' of undefined

### ISSUE THREAD

**Issue by mellatone** [Addepar/ember-table#382]
Hi. I'm running into `Uncaught TypeError: Cannot read property 'rebuild' of undefined` on line 303 of ember-table/components/ember-table

``` javascript
    updateLayout: function() {
      if ((this.get('_state') || this.get('state')) !== 'inDOM') {
        return;
      }
      // updating antiscroll
      this.$('.antiscroll-wrap').antiscroll().data('antiscroll').rebuild(); // line 303
      if (this.get('columnsFillTable')) {
        this.doForceFillColumns();
      }
    }
```

I'm using `ember-table 0.5.0`, `cli 0.2.0`, `ember 1.11.0`, and `jQuery 1.11.3`

If someone could point me to how to mock a CLI project in a jsbin, I'd be more than happy to do that as well (is that even possible?).

**Comment by bschouwerwou** [comment]
Not sure if it's the same scenario, but I'm encountering this error when trying to extend the component. I can use the component directly but that's not ideal.
```javascript
import TableComponent from 'ember-table/components/ember-table';
export default TableComponent.extend({
});
```
I'm using Ember 2.3 with CLI 2.2.0-beta.6 and have tried the ember-1.13 and ember-2.0 branches as well as artych@1181b1c mentioned in #374 .

**Comment by jaredtreeves** [comment]
If you are extending the ember-table it will throw this error unless you add a ember-table.hbs templete file to your project and copy the contents of the ember-table.hbs from the repo to the file you added. this should fix the issue. I think the the {{yeild}} is not working for this.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
