### ISSUE TITLE
Assertion Failed [removed in Ember 2.0]

### ISSUE THREAD

**Issue by DoronBrayer** [Addepar/ember-table#384]
After preforming a simple installation (`ember install ember-table`) in my new project - I get this build error:
"Assertion Failed: Using `{{view}}` or any path based on it ('smui/templates/body-table-container.hbs' @ L5:C8) has been removed in Ember 2.0"

**Comment by analysisi** [comment]
check the suppor version of ember from bower file

**Comment by DoronBrayer** [comment]
I am new at Ember. Can you be more specific please?
Thanks

**Comment by chwassme** [comment]
I'm having the same problem. My dependency to ember is "ember": "^2.0.0",

**Comment by chwassme** [comment]
ok, I think this is the problem. installing with "bower install ember-table --save" gave this:
ember#>=1.12 <1.13 which resolved to 1.12.1 and is required by ember-table#0.9.2

ember-table requires ember 1.12 (exactly this version!)

**Comment by cyril-sf** [comment]
Ember Table doesn't currently support Ember using Glimmer (so Ember 1.12 is the last version officially supported at the moment ).

There is an opened PR ( #374 ) if you want to use Ember Table w/ Ember 2.0.
