### ISSUE TITLE
Infinite loop when placed in flex box in FireFox

### ISSUE THREAD

**Issue by DanChadwick** [Addepar/ember-table#388]
`ember-table.js` contains:

``` javascript
  elementSizeDidChange: function() {
    if ((this.get('_state') || this.get('state')) !== 'inDOM') {
      return;
    }
    this.set('_width', this.$().parent().width());
    this.set('_height', this.$().parent().height());
    // we need to wait for the table to be fully rendered before antiscroll can
    // be used
    Ember.run.next(this, this.updateLayout);
  },
```

This sets the width to the parent's width. If the table has a border of, say, 1px and is positioned using flex layout, Firefox responds to this by widening the parent by 2px (1 for left and 1 for right). Chrome does not do this. This eventually calls `elementDidChangeSize` again with a width 2px wider. The symptom is that the app hangs FireFox, requiring a force-quit. Backburner has thousands of jobs queued up.

The simplest workaround is to ensure that the CSS does not use a left or right border, if this is graphically acceptable. I'm not sure what the correct fix is, especially given the browser inconsistency in flex layout.

I discovered this bug when placing an ember-table using Material Design, which uses flex layout.

**Comment by LydiaBarnes** [comment]
Thank you for bringing this bug to our attention! We are currently looking into improving table behavior in flex layouts.

**Comment by DanChadwick** [comment]
As a side note, putting the table in a flex container avoids having to set a fixed height on the container, which is what my use case needed.

**Comment by LydiaBarnes** [comment]
Can you let me know what your box-sizing is set to for the table and parent? I know Firefox doesn't do it quite right, and since this problem you're having is in Firefox, that jumps out to me.

**Comment by DanChadwick** [comment]
Both the parent and ember-table div are `box-sizing: border-box;`, Thanks, Lydia, for looking into this. It is appreciated.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
