### ISSUE TITLE
EMber 2.0 

### ISSUE THREAD

**Issue by analysisi** [Addepar/ember-table#389]
have plan to support ember 2.0? ember-grid is not good

**Comment by Glennvd** [comment]
There currently is a pull request that supports ember 2.0, but there are some performance issues that we're still facing. As for official ember 2.0 support, please refer to https://github.com/Addepar/ember-table/issues/337#issuecomment-156197786

**Comment by Blackening999** [comment]
Tracking the progress as well, very important for us

**Comment by analysisi** [comment]
@Glennvd my project not on ember-cli ,so i rebuild it ,i can use it in the ember 2.2 ,but i realy find some performance issues , in ember 1.12,use collectionview, when move scrollbar ,don't need to create new childitem compoent,  in ember 2.0, use component render childitem component , 
on move scrollbar ,use lazyContent to get datasource, and then will create new childitem component ,maybe it will get some performance down ,just may be , 
![2](https://cloud.githubusercontent.com/assets/12759554/11584449/fc87f600-9a9e-11e5-83b2-9b243fe09253.png)
![3](https://cloud.githubusercontent.com/assets/12759554/11584448/fc868018-9a9e-11e5-86f0-4cb427578a46.PNG)
![4](https://cloud.githubusercontent.com/assets/12759554/11584450/fcbf36ec-9a9e-11e5-9707-4d04bd7bc468.PNG)
![clipboard](https://cloud.githubusercontent.com/assets/12759554/11584452/fd1ed7be-9a9e-11e5-96ec-bd191a4bafbe.png)

**Comment by analysisi** [comment]
i change the ember table > 1.13 code ,  use 20 column , 100000 row ,i test in the ember 2.0, and ember 1.12 version (ember-table) ,i think, it is the same . under is my code , just think about it spend on it .

![Uploading 5.PNG…]()
![Uploading 6.PNG…]()

**Comment by DanChadwick** [comment]
Are you using PR #337? If so, it might be better to comment there, since performance is one of the blockers for getting that PR merged.

**Comment by cyril-sf** [comment]
@analysisi The answer is yes. We have been slow to work with community to upgrade to Ember 2.0 but this is definitely something we are planning on doing.

I'll close this issue as there is already PR ( #374 ) and we can continue the conversation there.
