### ISSUE TITLE
2 tables bound to the same model don't update in realtime

### ISSUE THREAD

**Issue by pkamenarsky** [Addepar/ember-table#39]
I.e. when editing one table it's necessary to scroll down and up again in the other one so that the cells are actually reloaded with the new values. Is there a way to make real time reactions to model updates work?

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
