### ISSUE TITLE
Example of ember-table -w- column totals and/or averages?

### ISSUE THREAD

**Issue by gdufford** [Addepar/ember-table#393]
Still very new to Ember, my team has inherited code that makes use of ember-table. For a few of my cases I need table data with simple totals at the bottom, in a total row. Another need is a table of values with averages in the bottom row.

Are there any examples/bins/whatever I can reference (other than the financial/tree example) that will show me how to do this?

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
