### ISSUE TITLE
Ember.StyleBindingsMixin Documentation?

### ISSUE THREAD

**Issue by gdufford** [Addepar/ember-table#394]
The Ember Table API section says to look at the Ember.StyleBindingsMixin documentation for information on the styleBindings option. Does this documentation exist? I can't find it.

**Comment by lsavage92** [comment]
I have been unable to find any documentation as well. Just had to go in and manually trace the mixin :disappointed:

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
