### ISSUE TITLE
Consider using something other than jQuery UI

### ISSUE THREAD

**Issue by eventualbuddha** [Addepar/ember-table#396]
For us it adds 420KB raw / 280KB minified / 68KB gzipped. Is there an alternative that is smaller? Could ember-table depend on more focused libraries that provide the needed functionality? Is there a barebones version of jQuery UI ember-table could point to that has only the functionality required?

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
