### ISSUE TITLE
ember 2.0 not compatible 

### ISSUE THREAD

**Issue by erwin16** [Addepar/ember-table#405]
I tried to install and test the latest master code ...  installing from github ..
but I still run into an error , related to {{view}} usage .... what happens with ember 2.0 compatibility ?

File: library/templates/body-table-container.hbs
The Broccoli Plugin: [TemplateCompiler] failed with:
Error: Assertion Failed: Using `{{view}}` or any path based on it ('library/templates/body-table-container.hbs' @ L5:C8) has been removed in Ember 2.0
    at new Error (native)
    at Error.EmberError (/Users/yves/Developments/WIP/EMNER_2.5/library/bower_components/ember/ember-template-compiler.js:4406:21)

**Comment by SirZach** [comment]
well known and is being documented in #400

**Comment by DanChadwick** [comment]
The best-functioning 2.0 branch as of now is probably in @artych's fork. In upstream, the cyril/ember-2.0 branch also works, but always shows the native scroll bars. Both versions would need work to be production ready. I think both don't respond to window resizing, for example.

**Comment by gwak** [comment]
The window resizing issue seems to be related to the didInsertElement hook defined in the mixin managing window resizing being overridden when mixed in another class. Maybe it should be an event handler instead.

**Comment by DanChadwick** [comment]
@gwak - Haven't looked at it, but maybe something isn't calling `_super()`.

**Comment by Datamance** [comment]
Bump. Any progress on this?

**Comment by seacowcorby** [comment]
I grabbed @artych's fork and used the ember_2.2 branch yesterday. I fixed the resize problem by renaming the resize mixin's didRender method to registerHandlers, then called it from the ember-table component's didRender method. It worked fine after that.

**Comment by DanChadwick** [comment]
@seacowcorby Maybe make a PR against @artych's fork? Assuming he merges it, it would help everyone else.

**Comment by seacowcorby** [comment]
@DanChadwick Will do. Fixing a bunch of issues. Horizontal scroll bar is sorted. Fixed a weird issue where the table would scroll by itself. Working on the vertical scrollbar now. Will PR them once they've been tested properly.

**Comment by satheeq** [comment]
Is there a tentative release date of latest ember-table build with Ember2.0 compatible?

**Comment by jamiechong** [comment]
Is there any update on Ember 2 compatibility?

**Comment by ArtemAlagizov** [comment]
yo, is the component still alive? are there plans to support Ember 3 in the future?

**Comment by ltegman** [comment]
Spoke with some of the addepar people at EmberConf and they said they're actively working on it and hoping to have it updated to Ember 2 within 6 months. Hopefully one of them can chime in on this thread with some official news or info on where people can find a development branch to contribute to/test out.

**Comment by pzuraq** [comment]
Hey all, I'm closing this issue in favor of #418.

The short answer is yes, we are planning on releasing a new version soon! We've been hard at work on a next generation occlusion library, [vertical-collection](https://github.com/html-next/vertical-collection), to replace Ember.ListView. Now that it's nearly complete we're planning on working on the next generation.

We'd love your feedback, feel free to add any thoughts to the main discussion issue or ping us in #e-table on the Ember Community Slack!
