### ISSUE TITLE
Request for sparkline example similar to the starter kit example

### ISSUE THREAD

**Issue by VincentRichard555** [Addepar/ember-table#409]
I would like to request an example for the sparkline table, similar to the one found here:

http://emberjs.jsbin.com/bihemir/edit?html,css,js,output

I have a stackoverflow question currently open where I try to create this, but fail due to some modifying of the empty-cell. Here is that link:

http://stackoverflow.com/questions/39482712/ember-table-sparkline-first-cell-does-not-plot-fulll-code-included

Thanks

**Comment by pzuraq** [comment]
Looking back at the history, it seems like `empty-cell` was an empty template. Not sure at what point or why the sparkline example stopped working, but we can work on getting a similar example working in v2. I'll also dig back in when I get a chance to see what's wrong with it in v1.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
