### ISSUE TITLE
Unselecting

### ISSUE THREAD

**Issue by ofridagan** [Addepar/ember-table#413]
Is there a way to unselect a row?
Or even just reset the selection?
Thanks.

**Comment by pzuraq** [comment]
It doesn't look like there is currently, but we can definitely look into addressing this for v2!

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
