### ISSUE TITLE
Using without ember.js

### ISSUE THREAD

**Issue by ugurerkan** [Addepar/ember-table#414]
Hello,

I need to use ember-table without ember.js 😝 
I know seams silly but let me explain 😄 , I have a simple app which is built around jQuery and need to display a financial table, when look around we found ember-table is the best solution but I can't implement ember.js now.

So, I need a workaround like solution, is there anyone have advice 🤔

**Comment by MelSumner** [comment]
@ugurerkan other non-Ember options exist, like jqwidgets grid. But why not try out your app in Ember?

**Comment by ugurerkan** [comment]
Thank you @MelSumner  ☺️ I was don't know jqwidgets 🤔 

I was try to adept finance table at this time with jQuery. Created a plugin which is simply collapses table's tbody by clicking previous thead. Will be share on github soon.

The reason for not I'm not using Ember is our app prototype now and need to change fast everything. I am more flexible without frameworks so decided to build with jQuery and yeoman-webapp stack ☺️

**Comment by pzuraq** [comment]
Hey @ugurerkan, totally understand that Ember may be too heavy-weight of a solution for your project but this library does make heavy use of Ember concepts and can't really be separated out from them 😕 

Like @MelSumner pointed out, there are alternatives that are non-Ember based out there. Maybe one day if the web components spec is ever finalized we can make it compatible with other libraries/frameworks, but for the foreseeable future this will be an Ember-only project.
