### ISSUE TITLE
How to implement Ember-table in ASP.net without MVC

### ISSUE THREAD

**Issue by yogeshwari15** [Addepar/ember-table#416]
Hi,

I want to implement Ember-table (Tree & financial table) in ASP.Net. I am not using MVC in my porject. Please guide me  to implement Ember-table in ASP.net without MVC.

Thanks,
Yogeshwari

**Comment by pzuraq** [comment]
Hi @yogeshwari15 

I'm sorry but I'm not sure we can help you there. Ember Table is an Ember-based library and requires the use of the [Ember Javascript framework](https://emberjs.com/). If you _are_ using Ember, or want to adopt it, let us know and we can try to help you out!
