### ISSUE TITLE
Cannot find module 'ember-table/models/column-definition

### ISSUE THREAD

**Issue by newton3** [Addepar/ember-table#423]
Just following the hello world example and failed.
I checked the addon source code and could not find models/column-definition in the /app folder. It does exist in /components.

PS - I am using typescript and it is unable to resolve. 

Please suggest the correct way.

**Comment by pzuraq** [comment]
Hey @newton3, we're currently in the middle of a rewrite for Modern versions of Ember. ET1 is not compatible with Ember 1.13+, check out our progress on the [v2.0](https://github.com/Addepar/ember-table/tree/2.0) branch instead. We'll be releasing the alpha sometime later this month.

**Comment by newton3** [comment]
oh that explains, thanks. 
Probably would have saved time  if you mentioned this on the repo home itself :). Here is the versions I have - just to double check that it is not compatible.

ember-cli: 2.12.0
node: 7.7.3

**Comment by pzuraq** [comment]
That is correct, 2.12 is not yet supported. I'm going to close this for now, but like I said the alpha will be coming out soon
