### ISSUE TITLE
row.collapse is crashing

### ISSUE THREAD

**Issue by csukda** [Addepar/ember-table#437]
I tried to collapse and expand rows manually and show a "+" or "-" sign when collapsed or not. So I had to access the collapse attribute. I collapsed the rows initially by calling collapseNode. After that it crashes by changing the collapse attribute with "row.collapse =" when calling expand or collapseNode. Exchanging "row.collapse=" with "Ember.set( )" solves this problem.

**Comment by billy-addepar** [comment]
@csukda you're right. It should be using `set` instead of direct property access. 

Can you open a PR to fix that? Also note that we avoid using global Ember name space. Import the `set` instead. Example: https://github.com/Addepar/ember-table/blob/master/addon/components/ember-table.js#L11
