### ISSUE TITLE
Weird bug while collapsing nodes

### ISSUE THREAD

**Issue by wuarmin** [Addepar/ember-table#439]
Hello,
we encountered a weird bug, but we can't fix it so far :(...

You can reproduce it with following steps:

Collapse Group 2
![grafik](https://user-images.githubusercontent.com/9987680/32504044-20d00730-c3df-11e7-8eba-386044f7ed10.png)
 
After that collapse Header 0
![grafik](https://user-images.githubusercontent.com/9987680/32504105-4fc7d16c-c3df-11e7-96f2-b29468dd8102.png)

After that try to expand Header 0...
You will get following error
TypeError: this.pointerNode is null 
from within the LinkedListTree::objectAt-method

We weren't able to find the issue. We think there's an issue with **originalPrevious**-member of TreeNode. We investigated the collapseNode and expand methods. Maybe you can help us. 

Thank You

**Comment by billy-addepar** [comment]
Thanks for reporting. I am looking into this.

**Comment by billy-addepar** [comment]
@wuarmin the bug is fixed in master now. You can point to fixed commit in your package.json if you want to use it.

**Comment by wuarmin** [comment]
Great! Thank you!
