### ISSUE TITLE
How to print a table...on paper (alpha)

### ISSUE THREAD

**Issue by tythewebguy** [Addepar/ember-table#457]
Before I get flamed for asking, this is a requirement I'm working on.

Is there a way to successfully print a table...on paper? It appears the occlusion and lazy rendering makes it difficult, or maybe impossible.

**Comment by pzuraq** [comment]
I think we can expose this as an option, it's something we actually included in the underlying occlusion library, [vertical-collection](https://github.com/html-next/vertical-collection). The option there is `shouldRenderAll` and we can likely just pass it through.

Note, rendering all elements will be a major perf degradation, there is no way around that. If you have to render everything, it's going to cost you.

**Comment by tythewebguy** [comment]
Totally understand the hit to performance, and the users will just have to accept that. I'll try it out and see what happens!

BTW, I was reading your article on `vertical-collection` this morning (_Rendering 10 Million Items..._) It was very helpful for understanding what's happening under the hood. So simple, and yet complicated. Thanks for taking the time to walk through the process and explain things.

**Comment by wuarmin** [comment]
@tythewebguy can you please post the link to the vertical-collection article. I'm very interested? 
Thx

**Comment by tythewebguy** [comment]
@wuarmin, here you go:

https://medium.com/build-addepar/rendering-10-million-items-with-vertical-collection-and-ember-js-3b8a4342cc84

**Comment by wuarmin** [comment]
@tythewebguy thank you

**Comment by tythewebguy** [comment]
Just got this working. Found the property name is `renderAll` and just needs to be passed to the `vertical-collection` component where it's used in `ember-table.hbs`, as suggested.

@pzuraq, thanks for pointing me in the right direction!

**Comment by tythewebguy** [comment]
@pzuraq your suggestion worked great. I just passed the `renderAll` to the ember-table and things worked beautifully.

We're looking to deploy soon with this functionality. Any chance I can submit a PR with this change?

**Comment by pzuraq** [comment]
Yeah, that would be great! We should also try to add a test, thanks for pushing it through!

**Comment by tythewebguy** [comment]
I just submitted the PR without a test--it's been a while since I've written tests, so I'll use this as a refresher when I have some time. :-)
