### ISSUE TITLE
"Assertion Failed: Cannot call get with 'length' on an undefined object" using master branch and Ember 2.17.0

### ISSUE THREAD

**Issue by cojomojo** [Addepar/ember-table#471]
I am trying to use ember-table (using the master branch) with Ember 2.17.0 but I am running into an error that I have not been able to get past. 

Here is my template:

```hbs
{{#ember-table
	rows=rows
	columns=columns
	as |row|}}
	{{#ember-table-row
		row=row
		as |cell|}}
		{{cell.value}}
	{{/ember-table-row}}
{{/ember-table}}
```

Here is my route.js:
```js
import Route from '@ember/routing/route';
import { A } from '@ember/array';
import computed from '@ember/object/computed';

export default Route.extend({
	columns: [
		{ columnName: 'Last Name', valuePath: 'lastName' },
		{ columnName: 'First Name', valuePath: 'firstName' },
		{ columnName: 'IsActive', valuePath: 'isActive' },
		{ columnName: 'Username', valuePath: 'username' },
	],

	rows: computed(() => {
		let rows = A();
                rows.pushObject({lastName: 'Smith', firstName: 'John', isActive: true, username: 'jsmith'});
		return rows;
	}),

	/**
         * Gets all people.
	 * @override
         * @method model
         * @return {Promise} promise
         */
	model() {
		let query = {
			page: 1,
			records: 100
		};
		return this.store.query('people', query);
	}
});
```

Output of ember version: 

```
ember-cli: 2.17.2
node: 6.11.2
os: win32 x64
```

Has anyone tried the latest code with 2.17 and come across this error? I noticed the package.json is still on 2.16.

**Comment by billy-addepar** [comment]
@cojomojo I ran ember-table with Ember 2.17 and did not see any issue in demo app

**Comment by billy-addepar** [comment]
You can also install 2.17 on your local machine and open `localhost:4200/demo` to verify if table works with 2.17.

**Comment by opendba** [comment]
I tried your test case, it needs following changes to make it work:
* move `columns` & `rows` properties from route to controller (or override `setupController` like it's done in `dummy/app/routes/subcolumns.js`)
* import of computed should be changed to:
```
import { computed } from '@ember/object';
```
![image](https://user-images.githubusercontent.com/6765564/34482274-96a08456-efbf-11e7-84c9-9a1f240e0c07.png)

**Comment by lkordys** [comment]
Hi,
I am also trying to use this component in my project but with no results.  Are examples on website:
http://opensource.addepar.com/ember-table/ still working?  @opendba  Your solution is working for me with this example but it shouldn't works like draging&dropping style? Why sometimes we use  "ColumnDefinition" and sometimes just create a simple JS array? (first solution isn't working for me, getting error from the issue title: "Assertion Failed...")

**Comment by wuarmin** [comment]
@lukkor89 you have to checkout the code examples at dummy-app. The guide on http://opensource.addepar.com/ember-table/#/overview is obsolete. It's the guide for pre 1.0. We are using ember-table with latest ember and have no problems with it.

**Comment by lukkor89** [comment]
Thanks for quick answer. I don't know how to checkout code to this branch - dummy-app.
What is the address for this app so I could checkout it? I'm using also #ember-table from now on but still it's displaying like normal array's elements:
![image](https://user-images.githubusercontent.com/17786053/34835448-2119bf4e-f6f5-11e7-801a-a65fad5a8ba5.png)
![image](https://user-images.githubusercontent.com/17786053/34835505-4e7c7850-f6f5-11e7-9650-6bf4a7d465b2.png)
![image](https://user-images.githubusercontent.com/17786053/34835524-5abfd4c2-f6f5-11e7-9707-a33b3ad51f84.png)

**Comment by pzuraq** [comment]
The dummy app is the app that is used for tests and demonstrations in Ember Addons. You can run the code locally by cloning this repo, running `yarn` and `ember s`. You can find the code at `/tests/dummy`
