### ISSUE TITLE
Compatibility with Ember pre-v2?

### ISSUE THREAD

**Issue by thebradbain** [Addepar/ember-table#474]
The project we're trying to integrate the current pre-release of ember-table v2.0.0 into is running on Ember 1.13.13,  however when serving up the app we get the following error: 

```
Cannot read property 'apply' of undefined
TypeError: Cannot read property 'apply' of undefined
    at Class.treeForApp (xyz\node_modules\ember-table\node_modules\@html-next\vertical-collection\index.js:141:40)
```

Which stems from the fact that pre-Ember-CLI 2.13.x or so, the dependency html-next/vertical-collection simply isn't compatible, as earlier versions of ember do not have access to `this._super` when exporting addons and building the tree for the app, it seems.

Is ember-table supposed to only support newer versions of ember? And if not, is there a known workaround for getting around the vertical-collection dependency? Thanks.

**Comment by billy-addepar** [comment]
@pzuraq

**Comment by billy-addepar** [comment]
Ember table should support all Ember versions from 1.11 till latest (2.17). I am not sure what is failing with vertical-collection on your side. It could be some build failure. @pzuraq

**Comment by billy-addepar** [comment]
Do you notice that you have 2 `node_modules`folder  in your error path? Are you linking `vertical-collection` locally? 

Have you try removing your `node_modules` folder and rebuild everything again?

**Comment by pzuraq** [comment]
The issue is that we support Ember@v1.11+, _not_ Ember-CLI@v1.11+.  It's a common misconception that you have to use the same version of `ember-cli` with Ember, but you can actually use modern Ember-CLI with as old of a version of Ember as you want (might change with Ember-CLI@v3). 

We're currently using Ember-CLI@v2.14, and we'll try to support older versions of Ember-CLI but we can't make any commitments at this time.

**Comment by thebradbain** [comment]
You learn new things every day! Do you know of any resource guides regarding using a different version of ember-cli with ember? I had always thought they shared npm dependencies.

**Comment by pzuraq** [comment]
You should be able to bump the version and update associated dependencies, and everything should Just Work for the most part. Some of your Ember-CLI code may need to be updated, but the Ember code will be self-contained in the single file imported from Bower components (and later, `ember-source`).

**Comment by thebradbain** [comment]
Thanks so much! That more or less took care of everything.
