### ISSUE TITLE
More examples of advanced working table

### ISSUE THREAD

**Issue by lukkor89** [Addepar/ember-table#477]
Hi,
do You have any more examples of using this component in more advanced usage?
I have found two tables in dummy app but still not getting how to add my own cell template for specify column. or how to use sorting by clicking in column header. I'm using: 

> Ember Data - 2.18
> Ember CLI - ^2.18.0
> Ember - 2.14.1
> Ember-table - alpha version.

**Comment by wuarmin** [comment]
@lukkor89 
custom cell/header-component can be set at column-definition i.e.:
```javascript
{
  columnName: 'Amount',
  valuePath: 'amount',
  width: 90,
  isResizeable: false,
  isReorderable: false,
  isSortable: true,
  headerComponent: 'act-header',
  cellComponent: 'table-formatted-cell'
}, {
  columnName: 'DueDate',
  valuePath: 'dueDate',
  width: 80,
  isResizeable: false,
  isReorderable: false,
  isSortable: true,
  headerComponent: 'act-header',
  cellComponent: 'table-formatted-cell'
}
```
a header-component-hbs I use looks i.e.
```hbs
<div {{action "onSortColumn"}}>
  {{column.columnName}}
  {{#if column.sorted}}
    <span class="lt-sort-icon {{if column.ascending "fa fa-sort-asc" "fa fa-sort-desc"}}"></span>
  {{/if}}
</div>
```
because of using your own components you are able to enrich your table with lots of features:
sorting, filtering...etc..

**Comment by lukkor89** [comment]
@wuarmin thanks for fast response.
Have You meant header-component.hbs to use it as own header? In that way it isn't working for me.
Only if I add custom file to my templates/components/ember-table-header.hbs and edit it.

If I add file named 'act-header' and create it in templates/components/act-header.hbs it isn't working. Maybe I'm placing it in wrong place? Where it should be?

**Comment by wuarmin** [comment]
@lukkor89 You can create your components via 
`ember generate component act-header`
ember-cli will create the necessary files
```
installing component
  create app/components/act-header.js
  create app/templates/components/act-header.hbs
installing component-test
  create tests/integration/components/act-header-test.js
```
After that you can customize your js and hbs file and place the component-name 'act-header' at the
column-def(described above). This should work.

**Comment by lukkor89** [comment]
@wuarmin  thanks, it's working now. 
I think it would be nice to have built-in sorting feature in the future :)
Having many new components only for simple tasks like sorting/filtering it's not the best thing to do in project.

**Comment by billy-addepar** [comment]
@lukkor89 you can extend the custom header and send any action (not just sorting) from header to your application with `onHeaderEvent`. Example

https://github.com/Addepar/ember-table/blob/ac20cac64cff9b166c91bb994ad33e34c71bf9fb/tests/dummy/app/components/custom-header.js#L7

**Comment by pzuraq** [comment]
@lukkor89 the main issue with that is that we can't actually know _how_ you want to sort. Do you paginate the table? If so, that means sort has to be on the backend, not the frontend. For our usage of Ember Table, we have a massive data set that we can't sort on the frontend, so even though we don't paginate we also need to sort on the backend. You may also choose to sort in a webworker or another context so that you are non-blocking. 

I think we may be able to provide a better public API for sorting in the future, but for now because of the number of edge cases we decided to provide an escape hatch in the form of custom header components.

**Comment by pzuraq** [comment]
We actually ended up implementing sorting in the table, along with many other features. Check out the new docs site to see examples!
