### ISSUE TITLE
Number.isInteger is not supported by IE11

### ISSUE THREAD

**Issue by miketervela** [Addepar/ember-table#481]
From ember-table.js:
```@computed('numFixedColumns')
  get hasFixedColumn() {
    let numFixedColumns = this.get('numFixedColumns');
    return Number.isInteger(numFixedColumns) && numFixedColumns !== 0;
  }
```

Not sure if you plan to support IE11 but Number.isInteger is not natively supported by it

**Comment by billy-addepar** [comment]
@miketervela we do plan to support IE11. Thanks for pointing this out. I will come up with a fix for it.

**Comment by ctjhoa** [comment]
Quick solution which should is to add this in your `ember-cli-build.js` :

```js
module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    "ember-cli-babel": {
      includePolyfill: true,
    },
...
  });
...
});
```

This will enable https://github.com/babel/ember-cli-babel#polyfill which will include https://github.com/zloirock/core-js#ecmascript-6-number with `Number.isInteger` polyfill

**Comment by pzuraq** [comment]
The implementation for fixed columns has changed a lot, so this shouldn't be an issue anymore.
