### ISSUE TITLE
Support IE11

### ISSUE THREAD

**Issue by billy-addepar** [Addepar/ember-table#490]
Basic table rendering fails on IE11 after some recent change.

**Comment by pzuraq** [comment]
This should not be an issue any more, but we haven’t been running tests regularly in IE so hard to say. We should setup CI on Windows and get full cross platform coverage going.

**Comment by mixonic** [comment]
Closing per https://github.com/Addepar/ember-table/issues/819 dropping support for IE11 in 3.0.
