### ISSUE TITLE
Improve current API to support OOB (w/o customizations) experience

### ISSUE THREAD

**Issue by twokul** [Addepar/ember-table#494]
It would be great to clean up some boilerplate in the current API.

Consider the example:

```hbs
{{#ember-table rows=rows columns=columns as |row|}}
  {{#ember-table-row row=row as |cell|}}
    {{cell.value}}
  {{/ember-table-row}}
{{/ember-table}}
```

If one doesn't need to modify anything, one should just be able to:

```hbs
{{ember-table rows=rows columns=columns}}
```

**Comment by pzuraq** [comment]
Closing this since it's gone a bit stale, the new API will require you to yield at least once to define arguments on the header, body, and footer (if it exists)
