### ISSUE TITLE
Fixed columns does not work at master branch

### ISSUE THREAD

**Issue by wuarmin** [Addepar/ember-table#497]
Hello :smile: ,

we are using greate ember-table addon to achive a tree-table with fixed columns.
Today I updated our app to use latest commit from your master branch and suddendy fixedColumns does not work any more(I also checked the ember-table dummy-app and there's the same issue).

Do you know the reason?
The issue was introduced with commit 867d418e4f7cc460302656b051fd8866c36ce817

Further question:
Is possible to have two fixed columns yet?

best regards and thanks

**Comment by billy-addepar** [comment]
Some change in `ember-decorator` modifies table behavior. This should be fixed upstream. In the meantime, you can use 2195e7427f2ec12f8c55e7a213b34370bb65aba5 commit to continue. There is not much change since that commit to latest master.

**Comment by wuarmin** [comment]
@billy-addepar thanks for the info. 
Is it possible to have more than one fixed columns in future?

**Comment by billy-addepar** [comment]
@wuarmin  It could be. We are thinking about adding a field `isFixed` in each column data object instead of using `numFixedColumn` in the table. Do you only have fixed columns in the left only or do you have some fixed column in the middle?

**Comment by wuarmin** [comment]
@billy-addepar currently I just need fixed colums in the left.

**Comment by addepar-andy** [comment]
I think this was fixed with: https://github.com/Addepar/ember-table/pull/502

@wuarmin: let us know if current master works for you

**Comment by wuarmin** [comment]
@addepar-andy yes thanks! it works again at current master.
Could you clarify what's your roadmap regarding multiple fixed columns. @billy-addepar said your are planning to define isFixed at column-definition. Is there a lot of work to do to achieve this feature?

best regards

**Comment by pzuraq** [comment]
hey @wuarmin, we're currently in the middle of some pretty major refactors to the public API and styles in general. We should be landing some of these in the next few days, once that's complete I think we'll be ready to take a look at multiple fixed columns. Based on the new styles I don't think `isFixed` on column definitions will work, it'll need to be constrained to the first N columns.
