### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by billy-addepar** [Addepar/ember-table#523]
I find a consistent way to reproduce mem leak issue without switching route:
1) Goes to `scenarios/performance` route
2) Adds a checkbox in the template to hide/show table. This will destroy previous table and create a new one.
3) Scrolls down to middle of the table. Selects some row. Clicks on hide checkbox to hide it. Clicks it gain to show a new table. 
4) Repeat step 3 several times. 

Observe memory increase over time even with forced GC. I guess some of the event listener/observer is still being tied to the DOM even after table is destroyed.

**Comment by addepar-andy** [comment]
the iverson tests on my branch are dying on jenkins.  maybe because of this.
