### ISSUE TITLE
Header of fixed column is not sticky at Firefox

### ISSUE THREAD

**Issue by wuarmin** [Addepar/ember-table#545]
Hello,
Today I noticed, that header-items of fixed columns are not sticky. They disappear if table-body is scrolled. I'm on ubuntu and use FF 60.0. It works at Chrome.

Best regards

**Comment by pzuraq** [comment]
Unsure if this was something we missed, or if it's a bug caused by a recent change to firefox/safari. It looks like Safari's behavior has changed so that we can apply the same fix we have for Chrome to all browsers, so I'll submit a PR updating this.
