### ISSUE TITLE
is it possible to mix widthConstraint and fixed size columns?

### ISSUE THREAD

**Issue by jamesdixon** [Addepar/ember-table#561]
Me again :)

Is it currently possible mix `widthConstraint` and fixed size columns?

My use case is that I'm adding various button actions to my table and I'd like to keep those columns a fixed size. However, I want to take advantage of spreading the remainder of the columns across the available space.

Thanks!

**Comment by pzuraq** [comment]
That's an interesting use case, not something we really considered but definitely valid. I think in general the ability to say that a column has a fixed width and is not resizable, even if the rest of the columns are, should be added. Same thing with reordering. 

`widthConstraint` should definitely respect this as well, and that presents another edge case - resize is _disabled_, but `widthConstraint` is _enabled_, and only certain columns should be resized. Will need to think on the ideal API here, but maybe a `staticWidth: true` flag passed to the column which disables resizing _and_ forces the `widthConstraint` to skip that column? That would be out of line with reordering, which I think would just need a `reorderEnabled` flag on the column.

**Comment by pzuraq** [comment]
A lot of the logic for fixed columns, column reordering, and other things depends on being able to know the exact pixel width of a column. There may be some tricks we can do with `requestAnimationFrame` to allow more dynamic widths, or we could use our own logic to calculate percentage widths, but it gets tricky (what value do you update it to on resize?)

Definitely open to passing more than just number values for widths though, just would have to figure out all the details.

**Comment by jamesdixon** [comment]
@pzuraq makes total sense! Would a good first step be to only allow percentage-based columns when you're not using resizable columns? Seems like that could potentially reduce the complexity.

**Comment by cah-danmonroe** [comment]
I'll +1 the request to allow for percentages for column widths.  We wouldn't be using resizable nor reorderable columns.

**Comment by pzuraq** [comment]
You can now set `isResizable` on columns, going to close this issue for now. We still need to add percentage based widths, will open a separate issue for that.
