### ISSUE TITLE
is it possible to disable sorting on specific columns?

### ISSUE THREAD

**Issue by jamesdixon** [Addepar/ember-table#563]
Hi,

I'm trying to disable sorting on specific columns. I tried `isSortable: false` in the column definition, but I'm still seeing the `is-sortable` class applied. Am I missing something?

Thank you!

**Comment by cah-danmonroe** [comment]
I would also like to disable sorting on different columns.

**Comment by cah-danmonroe** [comment]
This is how I was able to disable sorting on my "delete" column (where I display a trashcan icon to delete the row).  

If there is a better way, please let me know.
```
{{#table.head
        columns=columns
        sorts=sorts
        onUpdateSorts=(action updateSorts)
        as |header|}}
        {{#header.row as |headerrow|}}
            {{headerrow.cell}}
        {{/header.row}}
    {{/table.head}}
```
```
columns: computed(function () {
        return [
            {
                name: '',
                valuePath: 'reviewed'
            }, {
                name: 'Medication',
                valuePath: 'nameInfo'
            }, {
                name: 'Directions for Use',
                valuePath: 'directions'
            }, {
                name: 'Related Condition',
                valuePath: 'condition'
            }, {
                name: 'Prescriber',
                valuePath: 'prescriber'
            }, {
                name: '',
                valuePath: 'delete'
            }];
    }),
```
```
updateSorts(sorts) {
        let newSorts = sorts.filter(function(sortObj) {
            return sortObj.valuePath !== 'delete';
        });
        this.set('sorts', newSorts);
    },
```

**Comment by pzuraq** [comment]
I'm working on adding `isResizable`, `isSortable`, and `isReorderable` options to all of the columns currently, you can see the progress on this branch: https://github.com/Addepar/ember-table/tree/pzuraq/feat/add-column-level-configs

The only remaining work is to add test cases. It's trickier than you might think, there are edge cases for a lot of the behaviors in here (for instance, disabling reorderability only really makes sense for columns at the edge of the table, and generally you don't want users to be able to reorder a column to that edge spot). Hoping to get it in this week!

**Comment by pzuraq** [comment]
This is now available in beta.4!
