### ISSUE TITLE
table not observing changes?

### ISSUE THREAD

**Issue by jamesdixon** [Addepar/ember-table#565]
Hi,

I'm seeing some cases where changes to a model aren't being reflected in the table.

Here's the scenario:

I load data from my route and pass the model into a component containing a table. The data displays properly.

I have an edit icon that when clicked, sets a `currentRecord` property on the component and displays a modal, which displays the details of that record. Through the modal I can change the details of that record. When saving, the `save` method is called on that record and persisted to the backend, which returns the updated record.

This all works fine except that after saving, the record details aren't updated in the table.  If I add an `each` statement to list out the records and then make a change to a record, I see the update in the list output by `each` but not in the table.

Is there something special I need to do to ensure things are syncing properly?

Thanks!

**Comment by jamesdixon** [comment]
One thing I did notice is that the table updates properly if I add a new record or delete an existing record (calling `destroyRecord` on the record).

**Comment by pzuraq** [comment]
Sounds like a bug, the table is updating whenever the items array itself changes, but you're correct that it's not watching individual keys of an item. I'll try to dig in soon. 

Thanks for all the bug reports/feature requests by the way! This is really great feedback to be getting 😄

**Comment by jamesdixon** [comment]
@pzuraq thanks for the quick reply!

Sorry, I don't want to be a pest 👍 I really appreciate everything and will contribute where I can. I just figured I may as well ask before I dive into anything.

**Comment by pzuraq** [comment]
This should be fixed by #567! I want to get a few more of the open issues resolved before the next beta, but this will be coming soon

**Comment by jamesdixon** [comment]
@pzuraq thanks!
