### ISSUE TITLE
Add ability to apply classes to table element?

### ISSUE THREAD

**Issue by bgentry** [Addepar/ember-table#578]
Some CSS frameworks (i.e. [Bootstrap](https://getbootstrap.com/docs/4.0/content/tables/)) work by applying classes to the `table` element:

```html
<table class="table table-sm">
```

However, ember-table does not currently offer a way to customize the `table` element in any way, [rendering only a static `<table>` tag](https://github.com/Addepar/ember-table/blob/0b77cdf1ac2ba50166202083f5182a4870294a8c/addon/components/ember-table/template.hbs).

Can we add the ability to add classes to the `table` itself? Passing `<EmberTable class="table">` actually just applies the classes to the wrapping `<div>` rather than the `<table>`. Maybe an optional argument to the component called `tableClass`?

```hbs
<EmberTable @tableClass="table table-sm">
```

**Comment by bgentry** [comment]
I realized right after posting this that the Bootstrap styles actually do still work when the classes applied to the wrapping `<div>` 🤦‍♂️ . Gonna go ahead and close this, feel free to reopen if you do want this feature.

**Comment by pzuraq** [comment]
Glad it worked out for you. Just wanted to address this real quick in case people are wondering in the future, I'm generally against passing classes in as arguments (other than outerHTML semantics with `class`). It's not sustainable as an API practice, because it leads to an explosion of API space (e.g. adding an argument for every conceivable element that could be customized).

This is problematic for theming and especially for using CSS frameworks that come with styles for a specific HTML structure OOTB. I think this is a much more general problem though, and we don't really have great solutions for it. Currently, my favored path is using CSS preprocessors like SASS to fit the styles to the HTML structure. Well designed SASS/LESS/Stylus frameworks should make this doable, but not all off-the-shelf style frameworks are well designed 😕 

Maybe the answer is we do provide class name arguments for some things that are very likely to be customized (`table` tag, etc), but I'd like to explore other options before we commit to that as an API paradigm.

**Comment by jelhan** [comment]
> I realized right after posting this that the Bootstrap styles actually do still work when the classes applied to the wrapping

Only some of the styles are working for Bootstrap 4. E.g. the table is not using full width if `.table` is only present on wrapping `<div>`. It's not working at all for Bootstrap 3.

@pzuraq Please consider to reopen this one. I have to override template for `<EmberTable>` to apply a class required by Bootstrap. :disappointed:

**Comment by cluis13915** [comment]
Hello eveyone. I really need some classes to be applied to the <table> tag. Passing tagName='' to the component, throws this error. 

```
TypeError: Cannot read property 'getBoundingClientRect' of null
    at getScale (element.js:38)
    at Class.registerContainer (column-tree.js:697)
    at Class.didInsertElement (component.js:228)
    at Class.superWrapper [as didInsertElement] (ember-utils.js:428)
    at Class.trigger (core_view.js:62)
    at Class.superWrapper [as trigger] (ember-utils.js:428)
    at CurlyComponentManager.didCreate (ember-glimmer.js:4280)
    at Transaction.commit (runtime.js:2530)
    at Environment$1.commit (runtime.js:2616)
    at Environment$1.commit (ember-glimmer.js:3478)
```

**Comment by mixonic** [comment]
@cluis13915 

> I really need some classes to be applied to the table tag. Passing tagName='' to the component

I don't see what adding classes has to do with `tagName=''`. In classic invocation you can use `{{#ember-table class="custom-class-here"}}`. I think you can pass `@class="custom-class-here"` if you are using angle bracket invocation, but I'm not sure.

**Comment by cluis13915** [comment]
@mixonic Because passing tagName='' avoid the `div` wrapper and then the `classNames` are applied to the `table` tag. I'm not using angle bracket invocation because I'm in Ember 3.1.

```
{{#ember-table tagName="" classNames="table table-bordered table-hover table-condensed table-striped" as |t|}}
    ....
{{/ember-table}}
```

**Comment by mixonic** [comment]
Ah I see: https://github.com/Addepar/ember-table/blob/master/addon/components/ember-table/template.hbs#L1 The `table` is not the element of the component.

@cluis13915 there is no way to do what you're trying to do with public API of the addon. Using `tagName=''` will certainly not work, and there is no API for adding classes to the `<table>`.

In a parent component, a wrapper of ember-table you could use `didInsertElement() { run.schedule('afterRender', () => { this.element.querySelector('table').classList.add('some-class'); }) }`. But using the public API to add classes to the wrapping div or adding classes to a wrapper of your own and building styles that depend on that DOM seems like the most stable path forward.

**Comment by cluis13915** [comment]
@mixonic  OK. Thanks for your quick answer.

**Comment by Subaku** [comment]
Just came across this as I have the exact same issue. I did what @mixonic mentioned which was utilize `didInsertElement` since I didn't want to override anything and seemed to most sane solution.
