### ISSUE TITLE
table is not rendering

### ISSUE THREAD

**Issue by pranavdubase** [Addepar/ember-table#580]
I am trying to add new rows of data to ember table. But, it is not reflecting added rows of data.

**Comment by pzuraq** [comment]
Can you be more specific? How are you adding new rows?

**Comment by pranavdubase** [comment]
fetching data in route.js  
``` 
           return  RSVP.hash({
            rows:this.get('store').findRecord('rows',1),
           });
```
displaying in template.hbs
``` 
          {{#ember-table as |t|}}
          {{t.body rows=rows}}
          {{/ember-table}}
```  
adding new data to rows array in component.hbs
```     
         addData(rows)
         {
             let newRowData={ add new rows of data };
             rows.push(newRowData);
             this.get('store').findRecord('rows', 1,{ reload: true }).then(function (rowsPost) {
             rowsPost.set("rowsdata",rows);
             rowsPost.save();
            });
         }
``` 
I have checked after adding new row of data in ember record. it seems like updated.
thank you...

**Comment by pzuraq** [comment]
You need to use `pushObject` to mutate the state of the array, otherwise it won't trigger save correctly. Array mutations in general must follow the same rules for updating things like computed properties in Ember, using `set` or `pushObject`, etc.
