### ISSUE TITLE
EmberTable glimmer component should be referenced as Ember-Table in documentation

### ISSUE THREAD

**Issue by vihai** [Addepar/ember-table#585]
The examples from the docs refer to the ember-table component as <EmberTable>, however this raises the error:

```
Assertion Failed: You cannot use 'EmberTable' as a component name. Component names must contain a hyphen.
```

I guessed the proper tag name is <Ember-Table> and it seems to work. I suppose it should be fixed in the examples.

**Comment by pzuraq** [comment]
The docs are using the new angle bracket syntax which has been made available in Ember recently. We use the polyfill provided [here](https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill) which works on Ember 2.12+. This is addressed on the [legacy usage page](http://opensource.addepar.com/ember-table/latest/docs/guides/main/legacy-usage#usage-with-ember-2-3-2-11) of the documentation.

**Comment by pzuraq** [comment]
Actually, based on the other issue you opened it seems like you are using the angle brackets polyfill. What version of Ember are you using? You're only able to invoke the component as `<Ember-Table>`?

**Comment by vihai** [comment]
Yeah, I notice too late that the proper syntax is actually the one you are using in the docs. It's really tough to stay updated in this environment that is changing so quickly.

I'm using Ember 3.3.0 and reading this commit: e1b1ea482fede2c6c4043609e2e16db97d0d7307 it seems that  EMBER_GLIMMER_ANGLE_BRACKET_INVOCATION  has only been enabled starting from 3.4.0.

I upgraded and, in facts, it works.

**Comment by pzuraq** [comment]
awesome 😄 yeah lots of changes are coming soon, it's why we decided to go with the latest syntax for the docs (less maintenance in the future)
