### ISSUE TITLE
ember install/serve issue

### ISSUE THREAD

**Issue by cmackenz** [Addepar/ember-table#587]
After installing `ember-table` and running `ember serve` I get the following error.

``` shell
The Broccoli Plugin: [SimpleConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat ~/project/tmp/simple_concat-input_base_path-8NtsW5fI.tmp/0/node_modules/css-element-queries/src/ResizeSensor.js'
```

Ember version: **2.6.2**
npm: **6.2.0**

**Comment by cmackenz** [comment]
``` shell
ember-cli: 2.6.2
```

**Comment by cmackenz** [comment]
I believe this is the issue: 

https://github.com/Addepar/ember-table/blob/04cdf6defb8cfb953c74795d537e3e964c1fb491/index.js#L27

Ember versions < 2.15 cannot import directly from `node_modules`.

I've used [this](https://github.com/dfreeman/ember-cli-node-assets) addon in the past to support older versions of ember.

**Comment by pzuraq** [comment]
Ah, that makes sense. My recommendation for now is to upgrade Ember-CLI. It can be upgraded independently of Ember, we're currently running Ember-CLI 2.16 with Ember 1.12 at Addepar. Upgrading means you get all of the build benefits, even if you aren't on the latest Ember. I'm unsure if we'll be able to prioritize making Ember Table work with older versions of Ember-CLI.

**Comment by KevinGlinski** [comment]
upgrading ember cli from 2.13 fixed this for me

**Comment by devinrhode2** [comment]
@pzuraq Exactly how would one go about updating only Ember-CLI? just update ember-cli in the package.json? And you're saying nothing will break?

**Comment by devinrhode2** [comment]
Looks like just changing my `"ember-cli": "2.13.3"` to `"ember-cli": "2.18.2"` fixed this build error

**Comment by cmackenz** [comment]
FYI: We ran into a build issue when upgrading `ember-cli` from `2.6.2` to `2.16.0` due to an older version of `liquid-fire`. Upgrading `liquid-fire` to `0.27.3` resolved our issue.

Anyway, to wrap, it seems like updating `ember-cli` is pretty straight forward unless you are using an incompatible addon.

**Comment by cyril-sf** [comment]
Everything seems to be solved here, I'm closing the issue.
