### ISSUE TITLE
Column sorting is a twice-and-done thing

### ISSUE THREAD

**Issue by miketervela** [Addepar/ember-table#588]
If you click a column header once, it sorts descending.  If you then click a second time, it sorts ascending.  Click any more times after that and it stays ascending, unless you click another column and click back.  Looks like the culprit is here:

```
    if (!existingSorting) {
      newSortings.push({ valuePath, isAscending: false });
    } else if (existingSorting.isAscending === false) {
      newSortings.push({ valuePath, isAscending: true });
    }
```
If this column is not being sorted and is clicked, it will create a sort with isAscending = false.  Click again and the sort exists with isAscending false, so it changes the sort to isAscending true.  Click a third time, and the sort exists but is not isAscending===false so nothing happens.

Granted this isn't a huge issue, but if someone wants descending and accidentally double clicks to get ascending, they have to click away and back, which may not be intuitive.

**Comment by pzuraq** [comment]
In the example on the demo page, clicking the sorting column a third time turns the sort off. The sort will toggle between sorted asc, desc, and off repeatedly, which is the intended behavior: http://opensource.addepar.com/ember-table/latest/docs/guides/header/sorting

Can you post a reproduction of the issue?

**Comment by miketervela** [comment]
Ah, thanks for the link, I'm not handling the lack of sorts right on my end - I'll close. (also, I didn't know the mut helper could be used that way ,going to simplify this considerably - thanks!)
