### ISSUE TITLE
Getting default css style looks complicated and help docs can include some more tips.

### ISSUE THREAD

**Issue by kumkanillam** [Addepar/ember-table#595]
1. Getting the default CSS style steps are not straightforward in docs.The only below the line I found in docs which is not clearly explained.
`The rendered table is a plain table without any styling. You can define styling for your own table. If you want to use default table style, import the ember-table/default SASS file` 

this is what I did for getting the default CSS style.

I installed this addon used that demo and its working fine. but the default CSS styles are not included.
So to get the default styles I installed `@addepar/style-toolbox` addon. after that when I put build dist folder is missing `app-name.css`. 

- I created `app.scss` file in `app/styles` folder and  included this line `@import '@addepar/style-toolbox/index.scss';`. 
- Installed `ember-cli-sass` addon. 

Now everything is working fine. and default styles are included.

2. To use angle bracket component invocation We need to install the below addon `ember-angle-bracket-invocation-polyfill`.

The above points can be included in docs.

**Comment by pzuraq** [comment]
Point 2 is addressed in the docs on the [Legacy Usage](http://opensource.addepar.com/ember-table/latest/docs/guides/main/legacy-usage) page.

For point 1, our intention is not to provide opinionated styles out of the box. Addepar has its own unique style needs, and it's _not_ recommended that you use our style framework (`@addepar/style-toolbox`). Instead, we recommend that you write your own styles. We plan on including a section that guides you in how to write those styles, currently there is a [brief placeholder](http://opensource.addepar.com/ember-table/latest/docs/guides/main/styling-the-table).

**Comment by kumkanillam** [comment]
Thank you for your comments and this addon.
