### ISSUE TITLE
ember-table 2.0 production version

### ISSUE THREAD

**Issue by 0x9c** [Addepar/ember-table#599]
Hello everyone!

If I understood correctly the 2.0.0-beta.5 version has stable API which can be used in production.
But will be better to use the production version. What time approximately will be release the production version?

**Comment by pzuraq** [comment]
Unfortunately I don’t think we can give a definitive timeline at this point. We need to test out the new table as muxh as possible first, to get confidence that all of the details of the API are solid and won’t need to change.

**Comment by bantic** [comment]
Released [v2.0.0](https://github.com/Addepar/ember-table/releases/tag/v2.0.0)! 🎉
