### ISSUE TITLE
passing in a `selection` does not appear to work

### ISSUE THREAD

**Issue by efx** [Addepar/ember-table#624]
I realize maintenance for this addon is an open question (https://github.com/Addepar/ember-table/issues/622). Posting this issue for others using it. I can provide further reproduction on request. 
I am working with a table and have enabled multiple row selection. When a user clicks the table header row, I am implementing select all behavior that sets the `selection` property to an array of objects. This is passed into the component as `selection`. The component rerenders, but the checkboxes do not display as checked.
Does ember-table support loading selections by passing in an array to the `selection` attribute? The guides seem to say so: http://opensource.addepar.com/ember-table/latest/docs/guides/body/row-selection

**Comment by efx** [comment]
I was cloning an array of objects for `selection`. Hence, the first clause of this check failed because the objects did not equal each other: https://github.com/Addepar/ember-table/blob/master/addon/-private/collapse-tree.js#L75

**Comment by gwak** [comment]
@efx When you select all rows with some rows out of the viewport, and then uncheck one of the visible checked checkbox, does it work ?

**Comment by efx** [comment]
@gwak I have rewritten that section so I am unable to easily check right now. If you are able to put together a sample repo I could try from there; As an aside, I'm noticing some other odd behaviors using the multi selection option and clicking the table cell versus the row.
