### ISSUE TITLE
How can we implement Select/Unselect All functionality

### ISSUE THREAD

**Issue by gwak** [Addepar/ember-table#625]
Hi,

I'm currently trying to migrate one of our applications to use the new ember-table architecture, and I struggling to re-implement the selectAll/UnselectAll.

A checkbox controls a bool property `allSelected` and an action is triggered on clicking the checkbox `onToggleAll`.

```js
onToggleAll(checked) {
    set(this, 'allSelected', checked);
    set(this, 'tableSelection', checked ? this.rows : []);
},
```

At first it seems to work but when I try to unselect one of the row (by unchecking the row checkbox), I get an error:

`Assertion Failed: Cannot call get with '_parentMeta._rowValue' on an undefined object.`

When debugging the `RowMeta.select` function it seems that only visible rows have an existing RowMeta object instantiated, even though the array`rowMetas` is the same length as my selection. 
https://github.com/Addepar/ember-table/blob/4a922011e9c4142ff52e736aed0ca85d40bfdc7f/addon/-private/collapse-tree.js#L196

If I scroll into view all rows before the previous manipulations, everything works as expected, so I suspect the meta cache is only populated when the row component has been inserted into view at least once.

Thanks
Camille

**Comment by gwak** [comment]
I just found how to make it work, and it makes sense in retrospect...

You can't just set and replace the whole `selection` array as it won't trigger subscribed observers.
You need to clear the array and mutate it by pushing objects into it like so:

```js
onToggleAll(checked) {
  set(this, 'allSelected', checked);
  this.tableSelection.clear();
  if(checked) {
    this.tableSelection.pushObjects(this.rows);
  }
}
```

**Comment by gwak** [comment]
I've just tried to fix this issue in the PR below:
https://github.com/Addepar/ember-table/pull/626

**Comment by sanmaverick** [comment]
I am facing the same issue. Does your fix work for all cases?
I saw your comment on the bug - "Because of how vertical-collection works, the TableRowMetaCache is only populated for a given row when inserted into the DOM, when vertical-collection invokes objectAt(index) function of tree node.
We thus need to setup non-existent meta cache from selected rows."
I would really appreciate if you can elaborate on that statement. This would greatly help me understand the problem in detail.

Thanks,
Santhosh

**Comment by gwak** [comment]
@sanmaverick 
I'm not entirely sure how row meta mechanism works in EmberTable 2, but from what I understand, the TableRowMeta object for each row (which holds meta info like isSelected...) is setup here:

https://github.com/Addepar/ember-table/blob/7a52e8e16f9b8c99a2f84642583bfbe777bae7a5/addon/-private/collapse-tree.js#L573

The above call is found in the `objectAt` function of the `CollapseTree` class, which is only called from `vertical-collection` and only when actual row elements are created inserted into the DOM.

So when you try to add all models to the selection array, only the rows of the visible part of your table has meta object setup. When you then try to unselect a row, the below line returns an array equal in length to your rows array but with most of lines empty (apart from the visible ones):

https://github.com/Addepar/ember-table/blob/4a922011e9c4142ff52e736aed0ca85d40bfdc7f/addon/-private/collapse-tree.js#L196

So what my PR does is create a meta object when it doesn't exist already in that list when selecting/unselecting a row.

Hope it's clearer ?

**Comment by sanmaverick** [comment]
Makes sense. Thanks for the explanation and fix.
Any suggestions on how I can use this fix?
