### ISSUE TITLE
Compatible with ember-decorators v3

### ISSUE THREAD

**Issue by nightire** [Addepar/ember-table#632]
ember-decorators v3 has a breaking change which uses `@overridableReads` instead of `@reads` and uses `@reads` instead of `@readOnly` (both defined in `@ember-decorators/object/computed`, this, unfortunately, prevents us from using ember-table in our projects.

I understand the backward compatibility concerns, so maybe we can release a `@next` version that uses ember-decorators v3?

**Comment by cyril-sf** [comment]
I started to take a look at it. Please follow #664 to get more information.
