### ISSUE TITLE
Allow `fillMode` to to support placing the width delta in the nth column

### ISSUE THREAD

**Issue by chbonser** [Addepar/ember-table#634]
Currently the `fillMode` prop supports 3 options, `equal-column`, `first-column`, `last-column`. https://opensource.addepar.com/ember-table/latest/docs/guides/header/size-constraints#fill-mode

I'm proposing adding a `nth-column` option with a supporting `fillColumnIndex` prop. This will allow placing the width delta in a middle column.

I'll submit a PR soon with a working implementation.

**Comment by leimig** [comment]
+1

**Comment by cyril-sf** [comment]
Fixed with #635
