### ISSUE TITLE
Having 2 states(asc, desc) in sorting instead of the default 3(asc, desc, original order)

### ISSUE THREAD

**Issue by shankarsridhar** [Addepar/ember-table#636]
I guess this is more of a question rather than an issue.

AFAIK, ember-table, by default, toggles between the three states of sorting (ascending, descending, original order), when columns having sorting on them are clicked through.

I am trying to make the table column sort cycle only through 2 states - ascending and descending.

When using the column sorting on the table, is it possible to opt out of the 'original order' state from the set of sorted states the table column sorting, toggles through ?

**Comment by miketervela** [comment]
Assuming you are managing your 'sorts' array outside of the ember-table component and updating it in your onUpdateSorts action, you could do this:
in onUpdateSorts, if you get a blank array back, get your current sort array and if it has a single entry, toggle the isAscending property of it.  If you get any other value back, replace the sort array with the one you received as the action param.

This will probably only work on tables that only allow sorting by a single column at a time.

**Comment by bantic** [comment]
I'm going to close this because the suggestion by @miketervela is a good one (thank you!). Feel free to reopen if I'm mistaken.
I'm also going to create a new issue to add documentation for this to the "sorting" section of the docs.
