### ISSUE TITLE
ember-table@2.0.0-beta.6 breaking with ember-source@3.6

### ISSUE THREAD

**Issue by efx** [Addepar/ember-table#641]
<img width="1369" alt="screen shot 2018-12-14 at 11 04 56" src="https://user-images.githubusercontent.com/472721/50013792-21aa9100-ff90-11e8-80fd-f9f0a1f0b2a7.png">

The instance of `ember-thead` somehow as `undefined` for `this.unwrappedApi`: https://github.com/Addepar/ember-table/blob/master/addon/components/ember-thead/component.js#L49-L50. Happy to provide further debugging if needed.

The exception occurs somewhere in the render.

**Comment by efx** [comment]
I wonder if this is related to https://emberjs.com/deprecations/v3.x#toc_ember-meta-descriptor-on-object?

**Comment by twokul** [comment]
might be related to https://github.com/Addepar/ember-table/pull/633

**Comment by efx** [comment]
ah, thanks for the link @twokul; I can try the patch at some point next week.

**Comment by efx** [comment]
Verified this was resolved by #633 available in ember-table@2.0.0-beta.7
