### ISSUE TITLE
Tag latest beta (2.0.0-beta.7)

### ISSUE THREAD

**Issue by cyk** [Addepar/ember-table#655]
Currently, [`latest` tag](https://www.npmjs.com/package/ember-table?activeTab=versions) is to set to 2.0.0-beta.4.

There have been a few important fixes since, so I think we can avoid future duplicate issues reporting if we tag the latest version as 2.0.0-beta.7.

For example, I believe both https://github.com/Addepar/ember-table/issues/650 and https://github.com/Addepar/ember-table/issues/654 have [since been resolved](https://github.com/Addepar/ember-table/issues/641#issuecomment-448616889).

**Comment by bantic** [comment]
Updated the `latest` dist-tag to `2.0.0-beta.9`
