### ISSUE TITLE
Link in 'Styling the table' docs needs updating

### ISSUE THREAD

**Issue by shanemcgraw** [Addepar/ember-table#698]
It looks like the location of the table styles has moved in addepar-style-toolbox, which breaks this portion of the ['Styling the table' docs](https://github.com/Addepar/ember-table/blob/master/tests/dummy/app/pods/docs/guides/main/styling-the-table/template.md). It reads:

"You can check out the [table styles](https://github.com/Addepar/addepar-style-toolbox/blob/master/styles/components/table/_core.scss) applied there for inspiration."

But the link included points to a 404 page on Github. Can this be updated with the proper location?

**Comment by bantic** [comment]
Looks like this was fixed in #606, thanks for reporting!
