### ISSUE TITLE
Pagination?

### ISSUE THREAD

**Issue by es50678** [Addepar/ember-table#700]
Not sure if this is the right place, and if it's not hopefully I can be pointed in the right direction.
Is there a standard way to use pagination with ember-table? Is this a common problem, or such an uncommon use case for ember-table that there aren't any plans to integrate it into the repo?

**Comment by wuarmin** [comment]
Because of [vertical-collection](https://github.com/html-next/vertical-collection) ember-table can handle thousands of rows without problems. Therefore pagination is not that important for ember-table. What's your use-case?

**Comment by es50678** [comment]
for tables with a lot of data to load from the backend, without pagination we load them all at once and this can take a long time. We _could_ load everything incrementally and instead of traditional paging it's loads as the user scrolls down; we've done this before(not with ember-table). However, we'd prefer to have traditional paging. 
This isn't that important to us either, so feel free to close this if it's too much of a bother to integrate it.
Maybe we'll manage it and make a PR ;)

**Comment by wuarmin** [comment]
I understand your problem: If you do not load all at once, but in chunks (scroll to bottom), you have to implement sorting and filtering on server.

**Comment by mixonic** [comment]
@es50678 I think this is absolutely a valid issue. Ember Table shouldn't try to provide an end-to-end solution for lazy data fetching, but it should facilitate some hook for fetching new data when a user is scrolling/navigating (which you then need to translate to your own API).

I'm not sure if the original authors had a solution in mind here (cc @pzuraq @cyril-sf) but I definitely think it is something Ember Table should have a story around. On the other hand I don't have an immediately pressing need in our usage at Addepar, so I don't expect we will put any dev resources into solving this immediately.

I'm happy to meet and chat with anyone who had a pressing need and has time to tackle this.

**Comment by cyril-sf** [comment]
It's definitely something we had in mind, but as you guessed, it wasn't a top priority when we started the new implementation.

The main use case was that despite being capable of handling millions of rows and remaining performant, it's not necessarily wise to load all records in memory on the client side. Something close to an infinite scroll (while being finite) is probably a good example.

**Comment by es50678** [comment]
> I understand your problem: If you do not load all data at once, but in chunks (scroll to bottom), you have to implement sorting and filtering on server.
@wuarmin 
This is what we're doing now; since we have to implement it anyways for other things. 
And for the same reason the library doesn't currently have traditional paging, we can't dedicate the resources to add it in ourselves. 
Still, this is an amazing library and your suggestions have helped :).
