### ISSUE TITLE
Ability to add custom cell classes as available in `Ember Models Table`

### ISSUE THREAD

**Issue by kushthedude** [Addepar/ember-table#728]
#### Description :
Ability to add custom cell classes as available in `Ember Models Table`

Model Tables provide us with a way to use already defined CSS classes in table component like this :

```js
 colname : this.l10n.t('Completed Orders'),
        class   : 'ui green inverted segment center aligned',
        span    : 2
      }, {
        colname : this.l10n.t('Placed Orders'),
        class   : 'ui blue inverted segment center aligned',
        span    : 2
      }, {
```

But in ember tables we have no way customise the cells except custom CSS or colour addition, Provide the following feature in release `2.0`

**Comment by mixonic** [comment]
@kushthedude To add a class to a cell it is possible to do something like: `<r.cell class={{whatever-helper r}} />`. [This example in the docs uses `class=`](https://opensource.addepar.com/ember-table/docs/guides/main/table-meta-data#what-are-they-used-for-).

I think we are disinclined to add APIs for mapping row column definition data directly to attributes.

**Comment by bantic** [comment]
Closing this for now. @kushthedude, if this didn't answer the question, or if you have additional qs, please feel free to reopen!
