### ISSUE TITLE
Intercepting header click events

### ISSUE THREAD

**Issue by ryanto** [Addepar/ember-table#743]
Hello!

First, great job with this addon. I'm really digging it and the docs site is really well put together!

I'm in a situation where I need a click on the header column to fire an action that opens a modal, instead of sorting the table. I wanted to open an issue and see if there was any recommended way of doing that?

Right now I'm using `onUpdateSorts={{action 'columnHeaderClicked'}}`, but I don't get access to the full column with this approach, only the `valuePath`.

The other thought I had was putting an `a` tag to handle the action inside of the cell, but to get this working I had to override some margins.

```css
.table-header {
  padding: 0 !important;
}

.table-header-action {
  display: block;
  padding: 8px 4px;
}
```

```hbs
<h.row as |r|>
  <r.cell
    class="table-header"
    as |column|
  >
    <a
      {{on 'click' (action "columnHeaderClicked" column)}}
      class="table-header-action"
    >
      {{column.name}}
    </a>
  </r.cell>
</h.rows>
```

Just wanted to quickly ask what you think the best approach to having a custom header click handler would be?

Thanks again!

**Comment by bantic** [comment]
@ryanto Would looking up the column from the valuePath be an acceptable workaround for you? Like so:

```hbs
<t.head onUpdateSorts="onUpdateSorts">
```

```js
onUpdateSorts(sorts) {
  let [{ valuePath }] = sorts;
  let column = this.columns.find(c => c.valuePath === valuePath);
  this.handleClickOnColumn(column);
}
```

**Comment by ryanto** [comment]
Yup, absolutely acceptable! 

Just wanted to make sure I wasn't missing something like a click handler somewhere.

I'll close this issue. Thanks! 🎉
