### ISSUE TITLE
IE11 polyfill issue

### ISSUE THREAD

**Issue by ctjhoa** [Addepar/ember-table#759]
Hi,

We faced some issue with IE11.
In a new Ember app, without any specific configuration, in IE11, any table will not load.

![2019-09-06-150758_3837x1978_scrot](https://user-images.githubusercontent.com/1716173/64442056-ab6e3180-d0be-11e9-84a8-61b7f76b2496.png)

This is related to the `for ... of`  usage.

To work in IE11, users need to add this configuration in their `ember-cli-build.js` file:
```js
    'ember-cli-babel': {
      includePolyfill: true
    }
```

![2019-09-06-151722_1730x646_scrot](https://user-images.githubusercontent.com/1716173/64442823-12d8b100-d0c0-11e9-9c40-a4a59e7d83a8.png)

This is not documented and leads to complex installation flow.
In addition, there is no possibility to only include a polyfill set.

What I suggest, is to avoid the usage of `for ... of` which is not really needed and is transpiled to huge code block for a single loop.

https://babeljs.io/docs/en/babel-plugin-transform-for-of

Array's [forEach](https://api.emberjs.com/ember/3.8/classes/EmberArray/methods/forEach?anchor=forEach) should be used instead.

https://caniuse.com/#search=forEach

**Comment by mixonic** [comment]
@ctjhoa it seems like we could just document the requirement that one should use `includePolyfill` for IE11 support? I'd prefer to go in that direction.

**Comment by ctjhoa** [comment]
Enable `includePolyfill` is not without consequences for end users.
It force end users to include **all** polyfills to their project for **every browsers**.

I understand your decision from a project point of view but from a ember-table user this is costly for a browser which is still supported by ember (https://blog.emberjs.com/2018/02/14/ember-3-0-released.html)

**Comment by mixonic** [comment]
Something is fishy here. For/of is syntax and would be transpiled (sometimes, but not always, a transpilation needs a polyfilled). Array#forEach is an API and would always be polyfilled.

Anyway I think replacing array iteration with a plain for loop would be fine.

(Quickly, from my phone)

**Comment by ctjhoa** [comment]
@mixonic PR updated.
