### ISSUE TITLE
Table width includes scrollbar

### ISSUE THREAD

**Issue by frykten** [Addepar/ember-table#762]
Hi!

We've got a use-case where we need to scroll inside the table to see all the rows---the overflow is then on the `.ember-table` component. The issue seems to be with the size of the `table` tag: in `utils/element.js/` `getInnerClientRect()`, the JS method `element.getBoundingClientRect()` is used which is useful to find the boundaries of the element but not its client size since it counts the scrollbar as part of the width of the element...

It results as the last column being 'stomped on' by the *vertical-scrollbar (in red in the picture below)* and therefore the width of the `table` tag is now too wide for its `overflow: auto` parent and we get a *horizontal-scrollbar (in green in the picture below)*:
![CURRENT](https://user-images.githubusercontent.com/32638334/64700042-683d0580-d4a6-11e9-9bfd-62870c36664e.png)

In this picture, we can see that the table _(highlighted in blue by the browser in the picture below)_ is its `offset` parent width, goes under the _vertical scrollbar (in yellow in the picture below)_ and therefore the _vertical scrollbar (in red in the picture below)_:
![CURRENT_highlight](https://user-images.githubusercontent.com/32638334/64700270-deda0300-d4a6-11e9-8215-a9cfc4eeabd8.png)

What we aim to achieve, a vertical scrollbar _(in red in the picture below)_ that resides outside the table and normal flow _(no horizontal overflow, in green)_:
![GOAL](https://user-images.githubusercontent.com/32638334/64700148-a508fc80-d4a6-11e9-97ea-3765cbc75345.png)

We need to recalculate when the table is populated: depending on the number of rows, we may or may not need to overflow and can't have a blank space.

**Comment by ctjhoa** [comment]
Seems to be fixed et v3.x

**Comment by kpfefferle** [comment]
We added a `containerWidthAdjustment` option to `thead` in #637 specifically to address this usage and account for custom scrollbar widths. Can you give that a try?

**Comment by mixonic** [comment]
Based on merging https://github.com/Addepar/ember-table/pull/763 and the report that this is correct in 3.x, I'm going to close this issue.

Please let me know if I'm missing anything!
