### ISSUE TITLE
column width via own css

### ISSUE THREAD

**Issue by basz** [Addepar/ember-table#765]
Even when I use `@widthConstraint="none"` the table cells have inline css added as `width: 100px; min-width: 100px; max-width: 100px;`.

This prevents to specify column widths using custom css.

Am I missing something?

**Comment by paulyoder** [comment]
I believe ember table has to explicitly set the widths of each column so the sticky headers work correctly.

Have you checked out the [column width](https://opensource.addepar.com/ember-table/docs/guides/header/columns#column-width) section in the docs? (I assume you have but want to confirm)

**Comment by basz** [comment]
I have read it but missed I can set constraints myself. So thank you!
