### ISSUE TITLE
Ember table shim should be automated on release

### ISSUE THREAD

**Issue by danjamin** [Addepar/ember-table#78]
I have created a shim for ember table [ember-table-shim](https://github.com/danjamin/ember-table-shim) which is a temporary place for it.  This allows developers to install just the needed files through bower to get up and running instead of the entire project.

What should probably happen, is it should become part of the [Components](https://github.com/components) organization.

For now, it is easy enough to build and copy the files into the shim and tag the release.

However, this should become automated using something like [grunt-release-component](https://github.com/walmartlabs/grunt-release-component).

Then, it is simply a matter of changing ownership of the shim repo.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
