### ISSUE TITLE
Ember.get(...).some is not a function in Integration tests

### ISSUE THREAD

**Issue by Subaku** [Addepar/ember-table#798]
Trying to write some tests for my component that renders an EmberTable and I'm getting this error at the start of my tests.

<img width="798" alt="image" src="https://user-images.githubusercontent.com/1900930/71632716-ceb87180-2bc4-11ea-9f25-a174b9709518.png">

Here's the line that blows up.
<img width="785" alt="image" src="https://user-images.githubusercontent.com/1900930/71632744-f9a2c580-2bc4-11ea-9c13-47f4ea2c14a7.png">

Not doing anything special. Just rendering a very plain, simple table which works outside of tests just fine. Note this error happens upon rendering in my tests before any assertions.

Ember: 3.14.1

**Comment by mixonic** [comment]
@Subaku can you paste the test in here? It looks like there is no content being passed as rows?

**Comment by Subaku** [comment]
Thanks for the question. You made me realize the issue. I forgot I had to work around Ember Table not playing nice with Ember Data record arrays in my code and had to do `toArray()`. Forgot to do that in my tests so my issue is now fixed :)

Speaking of my problem though not entirely sure if it's something that you're aware of? Nothing stands out in the current issue's list. If not I can open a new issue. Either way thanks!

**Comment by xtagon** [comment]
I experienced this as well, it doesn't accept an AdapterPopulatedRecordArray. I got around this by using a computed property on `records.content` which is similar to the `.toArray()` technique but both seem like poor workarounds because it is not as observable to content changes.
