### ISSUE TITLE
opt-in IE11 / non-modern browser support

### ISSUE THREAD

**Issue by efx** [Addepar/ember-table#800]
While debugging a performance issue, I noticed that ember-table has IE specific checks:
https://github.com/Addepar/ember-table/blob/master/addon/components/ember-table/component.js#L48-L51
[ember-useragent](ua-parser-j) imports ua-parser-js which leads to unwanted code in vendor.js.

As a developer who does not need to support IE11, I would like to opt-in for cross-browser support.
It would be nice if these could be eliminated using a macro style approach that prunes unwanted code from the final build.

## related issues
#745, #490.

**Comment by mixonic** [comment]
Addepar no longer requires IE11 support so I am amenable to a major release dropping support. Or to some tweaks which make it IE11 support opt-out within 2.x.

It is a little unfortunate to ship a major fairly close to our recent major.

I welcome other perspectives @bantic @frykten @wuarmin or any others.

**Comment by efx** [comment]
> It is a little unfortunate to ship a major fairly close to our recent major.

Great point; I did not consider the semantic versioning guarantees. I would then vote for a tweaks approach.

**Comment by ctjhoa** [comment]
@mixonic Current Ember version still support IE11: https://github.com/emberjs/website/issues/3139#issuecomment-449216725
As ember-table is part of the ember ecosystem, IMO you should keep IE11 compatibility. I don't see the point of having addons which aren't aligned with their framework.
I completely understand that your company doesn't need it but it's an open source project in a wider ecosystem.

Anyway, if you drop support we'll be forced to fork ember-table.

**Comment by mixonic** [comment]
Please see https://github.com/Addepar/ember-table/issues/819 for a 3.0 plan. 2.x releases of Ember Table will of course continue to exist, however we're moving forward on a 3.0 plan which would mean a 3.0 final release without IE11 support probably some time in September.
