### ISSUE TITLE
Row cellValue not updating when columnValue.valuePath is updated (Ember >= 3.13.0)

### ISSUE THREAD

**Issue by napafundi** [Addepar/ember-table#808]
When using new versions of Ember (>= 3.13.0) ember-table isn't updating `row.cellValue` correctly even though `columnValue.valuePath` has been changed. This occurs when setting a new array of columns to the `table.head.columns` property.

Here is a simple Ember project displaying this issue:
[ember-table-issue](https://github.com/napafundi/ember-table-issue)

**Comment by billdami** [comment]
I can also confirm that this issue exists still even with the just released Ember v3.16.0 and v3.17.0-beta.1. Its worth noting that the first version of ember that this issue started occurring, 3.13, was the Octane "preview release", and contained a large amount of changes to Computed Properties, introducting tracked properties, etc. So it seems likely that this large internal changes to the object model have something to do with this bug.

For anyone else that encounters this, a very crude workaround can be implemented by forcing ember-table to recognize a change to the `rows` objects immediately after changing columns,  e.g. passing in a new temp array, and then changing it back to the original rows array in the next runloop:

```js
@tracked isChangingColumns = false;

@action
changeColumns() {
     //do something that changes `this.columns`...
    
    this.isChangingColumns = true;
    next(this, () => this.isChangingColumns = false);
}
```
```hbs
<T.body @rows={{if this.isChangingColumns (array) this.rows}} />
```
