### ISSUE TITLE
How do I create a tree table?

### ISSUE THREAD

**Issue by brian-gates** [Addepar/ember-table#81]
I feel like the example is the kitchen sink of examples; it includes a great deal more than is necessary.  Would love to see the simplest 'hello world' of tree table examples if possible.  Some documentation might help, too.

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
