### ISSUE TITLE
reorder not working

### ISSUE THREAD

**Issue by sharath-sriram** [Addepar/ember-table#820]
Using ember-cli 3.14, ember-table 2.2.2, column reordering does not work - as in, when the column is reordered, the rows do not change according to the new position of the columns. However, subsequent reorder operations after the first one work properly.

Before reorder: 
<img width="570" alt="Screenshot 2020-04-21 at 5 54 17 PM" src="https://user-images.githubusercontent.com/59554914/79865726-3fe09680-83f9-11ea-8c5f-80732b3f1b63.png">

After reorder (The contact column is pushed to the end)
<img width="572" alt="Screenshot 2020-04-21 at 5 54 55 PM" src="https://user-images.githubusercontent.com/59554914/79865758-4f5fdf80-83f9-11ea-9374-36188a5ce247.png">

As it can be noticed in the screenshots, even though the Contacts column has moved, the rows themselves have not moved. Am I doing something wrong? Is it an internal bug?

**Comment by sanmaverick** [comment]
I am observing this issue as well. Anyone else?

**Comment by lfcorrea** [comment]
It is happening with me too. The reorder is not working on Ember versions newer than 3.12 :(

Any news about it?

**Comment by EduardoLima806** [comment]
I am facing that same issue. Any guess estimate to solve it in the next release ?

**Comment by Valgueiro** [comment]
Any updates about this?

**Comment by sanmaverick** [comment]
Looking at the silence here, its likely that people have found a workaround? If there is a workaround for this, can someone please list it here?

**Comment by tempo22** [comment]
Hi,

I have been having the same issue. It is related to the `dynamicAlias` computed, I still haven't figured why but it seem that this computed is processed after the template

<img src="https://user-images.githubusercontent.com/1882437/95178510-d0e8d580-07bf-11eb-956e-ab9e3e1abfe3.png" width="400">

I made a quick fix on a fork but I'm sure there is a deeper problem in there:

```
diff --git a/addon/components/-private/row-wrapper.js b/addon/components/-private/row-wrapper.js
index 83c2221..f47b315 100644
--- a/addon/components/-private/row-wrapper.js
+++ b/addon/components/-private/row-wrapper.js
@@ -8,7 +8,9 @@ import { objectAt } from '../../-private/utils/array';
 import { dynamicAlias } from '../../-private/utils/computed';
 
 const CellWrapper = EmberObject.extend({
-  cellValue: dynamicAlias('rowValue', 'columnValue.valuePath'),
+  cellValue: computed('rowValue', 'columnValue.valuePath', function() {
+    return get(this.get('rowValue'), this.get('columnValue.valuePath'));
+  }),
 
   cellMeta: computed('rowMeta', 'columnValue', function() {
     let rowMeta = get(this, 'rowMeta');
```
