### ISSUE TITLE
Help - renderAll only in tests

### ISSUE THREAD

**Issue by Cabrafull** [Addepar/ember-table#828]
Hi everyone!,
is there a good way to render all the table when testing?

Maybe in the table template something like renderAll={{condition}}, and the condition depends on the environment. But i don't think this solution looks good.
Is there a way to force a table to renderAll when i write acceptance tests, for example new TablePage(renderAll) or something like that. While reading the docs I saw this piece of code:
```
let table = new TablePage({
  body: {
    rows: collection({
      isCustomRow: hasClass('custom-row'),
    }),
  },
});
```
So i thought that i could do something like that but for the renderAll option but i didn't manage to make it work.

Thanks!

**Comment by drewpereli** [comment]
@Cabrafull I do something like this. In the component that uses ember table, there's a property called "renderAll". 

```js
import Component from '@glimmer/component';
import ENV from 'my-app/config/environment';

export default class DataTable extends Component {
  renderAll = ENV.environment === 'test';
}

```

Then in the template, just set the `renderAll` argument on the table body to the `renderAll` property. 

```hbs
<EmberTable as |t|>
  <t.body @renderAll={{this.renderAll}} />
</EmberTable>
```

**Comment by mixonic** [comment]
I don't suggest doing this. Instead the test should actually scroll to the content, for example using https://github.com/emberjs/ember-test-helpers/blob/master/API.md#scrollto

Closing this on the basis of the use case here being an anti-pattern. Thank you, let me know if you have further perspective!
