### ISSUE TITLE
clarify license terms?

### ISSUE THREAD

**Issue by pombredanne** [Addepar/ember-table#836]
The license here is MIT https://github.com/Addepar/ember-table/blob/70d09600c0032f19cad1f62c050cde2d993e8365/package.json#L8
And here this is more or less a truncated BSD-3-Clause https://github.com/Addepar/ember-table/blob/70d09600c0032f19cad1f62c050cde2d993e8365/LICENSE.md  (See https://opensource.org/licenses/BSD-3-Clause )

It would be great if there could be a bit more clarity in the licenses and a standard license text.
Thanks!

**Comment by mixonic** [comment]
Agreed, it looks like in https://github.com/Addepar/ember-table/commit/48939919044baa2c71f360b1be13915c472360d9#diff-4673a3aba01813b595de187a7a6e9e63a3491d55821606fecd9f13a10c188a1dL1 there was a fat-finger which removed a pretty critical line of text from the license. I'll confirm with Addepar legal (as the copyright holders).

**Comment by mixonic** [comment]
Resolved by https://github.com/Addepar/ember-table/pull/850 in our 3.0-beta branch.

**Comment by pombredanne** [comment]
@mixonic Thank you ++
The FOSS license nerd in me is now happy :bow: 
`<plug>` FWIW I had found this in a license scan with https://github.com/nexB/scancode-toolkit  `</plug>`
