### ISSUE TITLE
Table resize bug of several instances

### ISSUE THREAD

**Issue by bolshchikov** [Addepar/ember-table#85]
The use case is the following. There are several instances of ember-table in different divs. However, only one of them is visible, all the rest of divs have property `display:none`. 
When the resize happens, the visible instance of ember-table behaves perfectly. However, when navigating to other divs (changing their display property to `block`), the table is not visible.
It happens when table instance listens to window.resize event, given the `display:none`, width and height of its container is 0.
Before:
![screen shot 2013-11-26 at 7 09 10 pm](https://f.cloud.github.com/assets/1206121/1624138/9392a69e-56bd-11e3-9bd5-e87b7507e1ff.png)
After:
![screen shot 2013-11-26 at 7 09 30 pm](https://f.cloud.github.com/assets/1206121/1624139/97b77600-56bd-11e3-8d29-c204e1b046d2.png)

**Comment by billy-addepar** [comment]
This version of Ember table is no longer supported. If you want to continue discussion, you can open the issue on [Ember Table Legacy](https://github.com/Addepar/ember-table-legacy)
