### ISSUE TITLE
Reordering headers does not reorder column data in >= 3.0

### ISSUE THREAD

**Issue by MichalBryxi** [Addepar/ember-table#899]
### Broken case

1. In docs go to any version that is [`v3.x.x` and above](https://opensource.addepar.com/ember-table/versions/v3.0.0/docs)
2. Click on "A Basic Table" section
3. Drag and drop one of the columns to other place
4. Notice that the header has changed position
5. Notice that the rest of the column data did not change position
6. Notice that the version of Ember here is `v3.24.2`

### Working case

1. In docs go to any version that is [below `v3.x.x`](https://opensource.addepar.com/ember-table/versions/v2.2.3/docs)
2. Click on "A Basic Table" section
3. Drag and drop one of the columns to other place
4. Notice that the header has changed position
5. Notice that the rest of the column data also did change position
6. Notice that the version of Ember here is `v3.12.0`

## Screenshots

![Screenshot 2021-07-28 at 22 21 47](https://user-images.githubusercontent.com/847473/127397853-40aefc1c-756e-4f3a-8ad1-0d53093a1993.png)

![Screenshot 2021-07-28 at 22 18 33](https://user-images.githubusercontent.com/847473/127397451-c19b40b7-c9ef-4783-81c6-48292f489710.png)

**Comment by MichalBryxi** [comment]
Note: In my own app where this bug is *present*, I use:

```
"ember-table": "^2.2.3",
"ember-cli": "~3.25.2",
```

So it _seems_ that the bug is introduced by higher version of `ember` rather than higher version of `ember-table`.

**Comment by loxmys** [comment]
demo page has same bug 
![ember-table-bug](https://user-images.githubusercontent.com/6581708/128500147-826dd1ae-8245-4451-8c8c-92f8af49bd98.gif)

**Comment by MichalBryxi** [comment]
Made me wonder whether that means that ember inspector suffers from this bug as well or not. Well it does :)

<img width="318" alt="Screenshot 2021-08-11 at 23 11 40" src="https://user-images.githubusercontent.com/847473/129110232-21349e67-9822-44bc-82d5-d95e8b376f2f.png">

**Comment by MichalBryxi** [comment]
Fixed in [v3.0.2-1](https://github.com/Addepar/ember-table/blob/master/CHANGELOG.md#v302-1) 🥳

**Comment by MichalBryxi** [comment]
PR that fixes this: https://github.com/Addepar/ember-table/pull/878
