### ISSUE TITLE
Remove ember-cli-sass dependency

### ISSUE THREAD

**Issue by fpauser** [Addepar/ember-table#903]
I use ember-cli-postcss in my projects and don't want to deal with 2 css compilers.

**Comment by kpfefferle** [comment]
I believe that this has been addressed by #900 which has been merged into the `4.0-beta` branch and is included with the `4.0-beta.0` prerelease. Ember-table@4 will no longer load ember-cli-sass as a dependency in consuming apps (though the dummy app continues to use it).

**Comment by nelstrom** [comment]
@kpfefferle thanks for the update. 

I see that in #900, `ember-cli-sass` has been moved from `dependencies: []` to `devDependencies: []`. Hopefully that will do the trick 🤞🏻
