### ISSUE TITLE
Antiscroll and Bootstrap 3

### ISSUE THREAD

**Issue by bkCDL** [Addepar/ember-table#93]
I don't know if this is a bug or merely a matter for documentation, but I found that when the parent element of {{table-component...}} is of class "container", antiscroll doesn't render right. The vertical scrollbar is hidden beneath it's parent.

I didn't see this mentioned in any conversations here, so I thought I'd mention it.

**Comment by drglitch** [comment]
This appears to have regressed - latest release is back to "outerHeight" which re-introduces this issue.
One way to fix this would be to wrap the entire table in an extra div with no paddings/margins, but it seems more appropriate to respect padding and margins on any existing container by using .height (not .innerHeight as in original fix) instead.
