### ISSUE TITLE
Proposal: Ember Table 5

### ISSUE THREAD

**Issue by mixonic** [Addepar/ember-table#957]
Building atop https://github.com/html-next/vertical-collection/issues/362 and https://github.com/html-next/vertical-collection/pull/372, I propose a 5.0 release of Ember Table.

* Support Ember 3.12+
* Require vertical-collection 4.x
* Change various calculations which rely on browser APIs that were presumed to return accurate values, but actually return rounded integers: https://github.com/Addepar/ember-table/pull/948
* Register the raf waiter as part of the setupForTest API https://github.com/Addepar/ember-table/issues/956
* Only document/test `<EmberTable />` style invocation over curly invocation.

What else?

**Comment by acorncom** [comment]
Those things look good on this end 👍
