### ISSUE TITLE
Making the table width 100%

### ISSUE THREAD

**Issue by rwwagner90** [Addepar/ember-table#974]
Am I missing something or is there no option to make the table full width? Are we supposed to just do this?

```css
.ember-table table {
  width: 100%;
}
```

I have been trying to find an option for allowing the table to grow to the width of the container, but it appears it will not unless you have manually added `width: 100%`.

It would be nice if we could add classes to the table element so we could pass Tailwind's `w-full` class to it.

**Comment by kpfefferle** [comment]
@rwwagner90 Check out Size Constraints: https://opensource.addepar.com/ember-table/docs/guides/header/size-constraints
